'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="FDA_XML_FOOD")>  _
Partial Public Class LGT_XML_FOODDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertXML_FOOD_EDIT_HISTORY(instance As XML_FOOD_EDIT_HISTORY)
    End Sub
  Partial Private Sub UpdateXML_FOOD_EDIT_HISTORY(instance As XML_FOOD_EDIT_HISTORY)
    End Sub
  Partial Private Sub DeleteXML_FOOD_EDIT_HISTORY(instance As XML_FOOD_EDIT_HISTORY)
    End Sub
  Partial Private Sub InsertXML_FOOD_PRODUCT(instance As XML_FOOD_PRODUCT)
    End Sub
  Partial Private Sub UpdateXML_FOOD_PRODUCT(instance As XML_FOOD_PRODUCT)
    End Sub
  Partial Private Sub DeleteXML_FOOD_PRODUCT(instance As XML_FOOD_PRODUCT)
    End Sub
  Partial Private Sub Inserttb_log_temp_food(instance As tb_log_temp_food)
    End Sub
  Partial Private Sub Updatetb_log_temp_food(instance As tb_log_temp_food)
    End Sub
  Partial Private Sub Deletetb_log_temp_food(instance As tb_log_temp_food)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("FDA_XML_FOODConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property XML_FOOD_EDIT_HISTORies() As System.Data.Linq.Table(Of XML_FOOD_EDIT_HISTORY)
		Get
			Return Me.GetTable(Of XML_FOOD_EDIT_HISTORY)
		End Get
	End Property
	
	Public ReadOnly Property XML_FOOD_PRODUCTs() As System.Data.Linq.Table(Of XML_FOOD_PRODUCT)
		Get
			Return Me.GetTable(Of XML_FOOD_PRODUCT)
		End Get
	End Property
	
	Public ReadOnly Property tb_log_temp_foods() As System.Data.Linq.Table(Of tb_log_temp_food)
		Get
			Return Me.GetTable(Of tb_log_temp_food)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.XML_FOOD_EDIT_HISTORY")>  _
Partial Public Class XML_FOOD_EDIT_HISTORY
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDA As Integer
	
	Private _FDPDTNO As String
	
	Private _LCTLCNNO As String
	
	Private _OBJ_CD As System.Nullable(Of Integer)
	
	Private _DES_OLD As String
	
	Private _DES_NEW As String
	
	Private _EDIT_DESCRIPTION As String
	
	Private _EDIT_REMARK As String
	
	Private _EDIT_REMARK_STAFF As String
	
	Private _SUB_OBJ_CD As System.Nullable(Of Integer)
	
	Private _ACTIVE As System.Nullable(Of Integer)
	
	Private _DATE As System.Nullable(Of Date)
	
	Private _CER_NUMBER As String
	
	Private _RCVNO As String
	
	Private _SYSTEM As String
	
	Private _EDIT_SPECIAL As System.Nullable(Of Integer)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnFDPDTNOChanging(value As String)
    End Sub
    Partial Private Sub OnFDPDTNOChanged()
    End Sub
    Partial Private Sub OnLCTLCNNOChanging(value As String)
    End Sub
    Partial Private Sub OnLCTLCNNOChanged()
    End Sub
    Partial Private Sub OnOBJ_CDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnOBJ_CDChanged()
    End Sub
    Partial Private Sub OnDES_OLDChanging(value As String)
    End Sub
    Partial Private Sub OnDES_OLDChanged()
    End Sub
    Partial Private Sub OnDES_NEWChanging(value As String)
    End Sub
    Partial Private Sub OnDES_NEWChanged()
    End Sub
    Partial Private Sub OnEDIT_DESCRIPTIONChanging(value As String)
    End Sub
    Partial Private Sub OnEDIT_DESCRIPTIONChanged()
    End Sub
    Partial Private Sub OnEDIT_REMARKChanging(value As String)
    End Sub
    Partial Private Sub OnEDIT_REMARKChanged()
    End Sub
    Partial Private Sub OnEDIT_REMARK_STAFFChanging(value As String)
    End Sub
    Partial Private Sub OnEDIT_REMARK_STAFFChanged()
    End Sub
    Partial Private Sub OnSUB_OBJ_CDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSUB_OBJ_CDChanged()
    End Sub
    Partial Private Sub OnACTIVEChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVEChanged()
    End Sub
    Partial Private Sub OnDATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDATEChanged()
    End Sub
    Partial Private Sub OnCER_NUMBERChanging(value As String)
    End Sub
    Partial Private Sub OnCER_NUMBERChanged()
    End Sub
    Partial Private Sub OnRCVNOChanging(value As String)
    End Sub
    Partial Private Sub OnRCVNOChanged()
    End Sub
    Partial Private Sub OnSYSTEMChanging(value As String)
    End Sub
    Partial Private Sub OnSYSTEMChanged()
    End Sub
    Partial Private Sub OnEDIT_SPECIALChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnEDIT_SPECIALChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FDPDTNO", DbType:="NVarChar(13)")>  _
	Public Property FDPDTNO() As String
		Get
			Return Me._FDPDTNO
		End Get
		Set
			If (String.Equals(Me._FDPDTNO, value) = false) Then
				Me.OnFDPDTNOChanging(value)
				Me.SendPropertyChanging
				Me._FDPDTNO = value
				Me.SendPropertyChanged("FDPDTNO")
				Me.OnFDPDTNOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCTLCNNO", DbType:="NVarChar(8)")>  _
	Public Property LCTLCNNO() As String
		Get
			Return Me._LCTLCNNO
		End Get
		Set
			If (String.Equals(Me._LCTLCNNO, value) = false) Then
				Me.OnLCTLCNNOChanging(value)
				Me.SendPropertyChanging
				Me._LCTLCNNO = value
				Me.SendPropertyChanged("LCTLCNNO")
				Me.OnLCTLCNNOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OBJ_CD", DbType:="Int")>  _
	Public Property OBJ_CD() As System.Nullable(Of Integer)
		Get
			Return Me._OBJ_CD
		End Get
		Set
			If (Me._OBJ_CD.Equals(value) = false) Then
				Me.OnOBJ_CDChanging(value)
				Me.SendPropertyChanging
				Me._OBJ_CD = value
				Me.SendPropertyChanged("OBJ_CD")
				Me.OnOBJ_CDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DES_OLD", DbType:="NVarChar(MAX)")>  _
	Public Property DES_OLD() As String
		Get
			Return Me._DES_OLD
		End Get
		Set
			If (String.Equals(Me._DES_OLD, value) = false) Then
				Me.OnDES_OLDChanging(value)
				Me.SendPropertyChanging
				Me._DES_OLD = value
				Me.SendPropertyChanged("DES_OLD")
				Me.OnDES_OLDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DES_NEW", DbType:="NVarChar(MAX)")>  _
	Public Property DES_NEW() As String
		Get
			Return Me._DES_NEW
		End Get
		Set
			If (String.Equals(Me._DES_NEW, value) = false) Then
				Me.OnDES_NEWChanging(value)
				Me.SendPropertyChanging
				Me._DES_NEW = value
				Me.SendPropertyChanged("DES_NEW")
				Me.OnDES_NEWChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EDIT_DESCRIPTION", DbType:="NVarChar(MAX)")>  _
	Public Property EDIT_DESCRIPTION() As String
		Get
			Return Me._EDIT_DESCRIPTION
		End Get
		Set
			If (String.Equals(Me._EDIT_DESCRIPTION, value) = false) Then
				Me.OnEDIT_DESCRIPTIONChanging(value)
				Me.SendPropertyChanging
				Me._EDIT_DESCRIPTION = value
				Me.SendPropertyChanged("EDIT_DESCRIPTION")
				Me.OnEDIT_DESCRIPTIONChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EDIT_REMARK", DbType:="NVarChar(MAX)")>  _
	Public Property EDIT_REMARK() As String
		Get
			Return Me._EDIT_REMARK
		End Get
		Set
			If (String.Equals(Me._EDIT_REMARK, value) = false) Then
				Me.OnEDIT_REMARKChanging(value)
				Me.SendPropertyChanging
				Me._EDIT_REMARK = value
				Me.SendPropertyChanged("EDIT_REMARK")
				Me.OnEDIT_REMARKChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EDIT_REMARK_STAFF", DbType:="NVarChar(MAX)")>  _
	Public Property EDIT_REMARK_STAFF() As String
		Get
			Return Me._EDIT_REMARK_STAFF
		End Get
		Set
			If (String.Equals(Me._EDIT_REMARK_STAFF, value) = false) Then
				Me.OnEDIT_REMARK_STAFFChanging(value)
				Me.SendPropertyChanging
				Me._EDIT_REMARK_STAFF = value
				Me.SendPropertyChanged("EDIT_REMARK_STAFF")
				Me.OnEDIT_REMARK_STAFFChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SUB_OBJ_CD", DbType:="Int")>  _
	Public Property SUB_OBJ_CD() As System.Nullable(Of Integer)
		Get
			Return Me._SUB_OBJ_CD
		End Get
		Set
			If (Me._SUB_OBJ_CD.Equals(value) = false) Then
				Me.OnSUB_OBJ_CDChanging(value)
				Me.SendPropertyChanging
				Me._SUB_OBJ_CD = value
				Me.SendPropertyChanged("SUB_OBJ_CD")
				Me.OnSUB_OBJ_CDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVE", DbType:="Int")>  _
	Public Property ACTIVE() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVE
		End Get
		Set
			If (Me._ACTIVE.Equals(value) = false) Then
				Me.OnACTIVEChanging(value)
				Me.SendPropertyChanging
				Me._ACTIVE = value
				Me.SendPropertyChanged("ACTIVE")
				Me.OnACTIVEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="DATE", Storage:="_DATE", DbType:="DateTime")>  _
	Public Property [DATE]() As System.Nullable(Of Date)
		Get
			Return Me._DATE
		End Get
		Set
			If (Me._DATE.Equals(value) = false) Then
				Me.OnDATEChanging(value)
				Me.SendPropertyChanging
				Me._DATE = value
				Me.SendPropertyChanged("[DATE]")
				Me.OnDATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CER_NUMBER", DbType:="NVarChar(8)")>  _
	Public Property CER_NUMBER() As String
		Get
			Return Me._CER_NUMBER
		End Get
		Set
			If (String.Equals(Me._CER_NUMBER, value) = false) Then
				Me.OnCER_NUMBERChanging(value)
				Me.SendPropertyChanging
				Me._CER_NUMBER = value
				Me.SendPropertyChanged("CER_NUMBER")
				Me.OnCER_NUMBERChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RCVNO", DbType:="NVarChar(MAX)")>  _
	Public Property RCVNO() As String
		Get
			Return Me._RCVNO
		End Get
		Set
			If (String.Equals(Me._RCVNO, value) = false) Then
				Me.OnRCVNOChanging(value)
				Me.SendPropertyChanging
				Me._RCVNO = value
				Me.SendPropertyChanged("RCVNO")
				Me.OnRCVNOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SYSTEM", DbType:="NVarChar(MAX)")>  _
	Public Property SYSTEM() As String
		Get
			Return Me._SYSTEM
		End Get
		Set
			If (String.Equals(Me._SYSTEM, value) = false) Then
				Me.OnSYSTEMChanging(value)
				Me.SendPropertyChanging
				Me._SYSTEM = value
				Me.SendPropertyChanged("SYSTEM")
				Me.OnSYSTEMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EDIT_SPECIAL", DbType:="Int")>  _
	Public Property EDIT_SPECIAL() As System.Nullable(Of Integer)
		Get
			Return Me._EDIT_SPECIAL
		End Get
		Set
			If (Me._EDIT_SPECIAL.Equals(value) = false) Then
				Me.OnEDIT_SPECIALChanging(value)
				Me.SendPropertyChanging
				Me._EDIT_SPECIAL = value
				Me.SendPropertyChanged("EDIT_SPECIAL")
				Me.OnEDIT_SPECIALChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.XML_FOOD_PRODUCT")>  _
Partial Public Class XML_FOOD_PRODUCT
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDA As Integer
	
	Private _pvncd As System.Nullable(Of Short)
	
	Private _lcnno As System.Nullable(Of Integer)
	
	Private _lcnsid As System.Nullable(Of Integer)
	
	Private _fdpdtno As String
	
	Private _lcntypecd As System.Nullable(Of Integer)
	
	Private _prdnmt As String
	
	Private _prdnme As String
	
	Private _Producer_Name As String
	
	Private _groupname As String
	
	Private _NewCode As String
	
	Private _Ranking As String
	
	Private _cntcd As String
	
	Private _appdate As String
	
	Private _expdate As System.Nullable(Of Date)
	
	Private _CreateDate As System.Nullable(Of Date)
	
	Private _UpdateDate As System.Nullable(Of Date)
	
	Private _rid As System.Nullable(Of Integer)
	
	Private _Cer_expdate As System.Nullable(Of Date)
	
	Private _Brand As String
	
	Private _thanm As String
	
	Private _Status As System.Nullable(Of Integer)
	
	Private _Addr As String
	
	Private _fdtypecd As System.Nullable(Of Integer)
	
	Private _fdtypenm As String
	
	Private _thanmowner As String
	
	Private _EXP As String
	
	Private _lctlcnno As String
	
	Private _CITIZEN_AUTHORIZE As String
	
	Private _SUBPDT As String
	
	Private _MTHCD As String
	
	Private _frgn_addr As String
	
	Private _LCN_STATUS As System.Nullable(Of Integer)
	
	Private _LCN_STATUS_NAME As String
	
	Private _FACTORY_TYPE As String
	
	Private _APPLICTION_TYPE As String
	
	Private _TAXNO As String
	
	Private _DOSAGE As System.Nullable(Of Double)
	
	Private _EXPDAY As System.Nullable(Of Integer)
	
	Private _SUBPDT_NM As String
	
	Private _MTHCD_NM As String
	
	Private _ACTIVE As System.Nullable(Of Integer)
	
	Private _FML As System.Nullable(Of Integer)
	
	Private _status_name As String
	
	Private _remark_product As String
	
	Private _remark_location As String
	
	Private _CANCEL_DATE As System.Nullable(Of Date)
	
	Private _APPROVE_DATE As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnpvncdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnpvncdChanged()
    End Sub
    Partial Private Sub OnlcnnoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcnnoChanged()
    End Sub
    Partial Private Sub OnlcnsidChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcnsidChanged()
    End Sub
    Partial Private Sub OnfdpdtnoChanging(value As String)
    End Sub
    Partial Private Sub OnfdpdtnoChanged()
    End Sub
    Partial Private Sub OnlcntypecdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcntypecdChanged()
    End Sub
    Partial Private Sub OnprdnmtChanging(value As String)
    End Sub
    Partial Private Sub OnprdnmtChanged()
    End Sub
    Partial Private Sub OnprdnmeChanging(value As String)
    End Sub
    Partial Private Sub OnprdnmeChanged()
    End Sub
    Partial Private Sub OnProducer_NameChanging(value As String)
    End Sub
    Partial Private Sub OnProducer_NameChanged()
    End Sub
    Partial Private Sub OngroupnameChanging(value As String)
    End Sub
    Partial Private Sub OngroupnameChanged()
    End Sub
    Partial Private Sub OnNewCodeChanging(value As String)
    End Sub
    Partial Private Sub OnNewCodeChanged()
    End Sub
    Partial Private Sub OnRankingChanging(value As String)
    End Sub
    Partial Private Sub OnRankingChanged()
    End Sub
    Partial Private Sub OncntcdChanging(value As String)
    End Sub
    Partial Private Sub OncntcdChanged()
    End Sub
    Partial Private Sub OnappdateChanging(value As String)
    End Sub
    Partial Private Sub OnappdateChanged()
    End Sub
    Partial Private Sub OnexpdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnexpdateChanged()
    End Sub
    Partial Private Sub OnCreateDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCreateDateChanged()
    End Sub
    Partial Private Sub OnUpdateDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnUpdateDateChanged()
    End Sub
    Partial Private Sub OnridChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnridChanged()
    End Sub
    Partial Private Sub OnCer_expdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCer_expdateChanged()
    End Sub
    Partial Private Sub OnBrandChanging(value As String)
    End Sub
    Partial Private Sub OnBrandChanged()
    End Sub
    Partial Private Sub OnthanmChanging(value As String)
    End Sub
    Partial Private Sub OnthanmChanged()
    End Sub
    Partial Private Sub OnStatusChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnStatusChanged()
    End Sub
    Partial Private Sub OnAddrChanging(value As String)
    End Sub
    Partial Private Sub OnAddrChanged()
    End Sub
    Partial Private Sub OnfdtypecdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnfdtypecdChanged()
    End Sub
    Partial Private Sub OnfdtypenmChanging(value As String)
    End Sub
    Partial Private Sub OnfdtypenmChanged()
    End Sub
    Partial Private Sub OnthanmownerChanging(value As String)
    End Sub
    Partial Private Sub OnthanmownerChanged()
    End Sub
    Partial Private Sub OnEXPChanging(value As String)
    End Sub
    Partial Private Sub OnEXPChanged()
    End Sub
    Partial Private Sub OnlctlcnnoChanging(value As String)
    End Sub
    Partial Private Sub OnlctlcnnoChanged()
    End Sub
    Partial Private Sub OnCITIZEN_AUTHORIZEChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_AUTHORIZEChanged()
    End Sub
    Partial Private Sub OnSUBPDTChanging(value As String)
    End Sub
    Partial Private Sub OnSUBPDTChanged()
    End Sub
    Partial Private Sub OnMTHCDChanging(value As String)
    End Sub
    Partial Private Sub OnMTHCDChanged()
    End Sub
    Partial Private Sub Onfrgn_addrChanging(value As String)
    End Sub
    Partial Private Sub Onfrgn_addrChanged()
    End Sub
    Partial Private Sub OnLCN_STATUSChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnLCN_STATUSChanged()
    End Sub
    Partial Private Sub OnLCN_STATUS_NAMEChanging(value As String)
    End Sub
    Partial Private Sub OnLCN_STATUS_NAMEChanged()
    End Sub
    Partial Private Sub OnFACTORY_TYPEChanging(value As String)
    End Sub
    Partial Private Sub OnFACTORY_TYPEChanged()
    End Sub
    Partial Private Sub OnAPPLICTION_TYPEChanging(value As String)
    End Sub
    Partial Private Sub OnAPPLICTION_TYPEChanged()
    End Sub
    Partial Private Sub OnTAXNOChanging(value As String)
    End Sub
    Partial Private Sub OnTAXNOChanged()
    End Sub
    Partial Private Sub OnDOSAGEChanging(value As System.Nullable(Of Double))
    End Sub
    Partial Private Sub OnDOSAGEChanged()
    End Sub
    Partial Private Sub OnEXPDAYChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnEXPDAYChanged()
    End Sub
    Partial Private Sub OnSUBPDT_NMChanging(value As String)
    End Sub
    Partial Private Sub OnSUBPDT_NMChanged()
    End Sub
    Partial Private Sub OnMTHCD_NMChanging(value As String)
    End Sub
    Partial Private Sub OnMTHCD_NMChanged()
    End Sub
    Partial Private Sub OnACTIVEChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVEChanged()
    End Sub
    Partial Private Sub OnFMLChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFMLChanged()
    End Sub
    Partial Private Sub Onstatus_nameChanging(value As String)
    End Sub
    Partial Private Sub Onstatus_nameChanged()
    End Sub
    Partial Private Sub Onremark_productChanging(value As String)
    End Sub
    Partial Private Sub Onremark_productChanged()
    End Sub
    Partial Private Sub Onremark_locationChanging(value As String)
    End Sub
    Partial Private Sub Onremark_locationChanged()
    End Sub
    Partial Private Sub OnCANCEL_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCANCEL_DATEChanged()
    End Sub
    Partial Private Sub OnAPPROVE_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnAPPROVE_DATEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pvncd", DbType:="SmallInt")>  _
	Public Property pvncd() As System.Nullable(Of Short)
		Get
			Return Me._pvncd
		End Get
		Set
			If (Me._pvncd.Equals(value) = false) Then
				Me.OnpvncdChanging(value)
				Me.SendPropertyChanging
				Me._pvncd = value
				Me.SendPropertyChanged("pvncd")
				Me.OnpvncdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnno", DbType:="Int")>  _
	Public Property lcnno() As System.Nullable(Of Integer)
		Get
			Return Me._lcnno
		End Get
		Set
			If (Me._lcnno.Equals(value) = false) Then
				Me.OnlcnnoChanging(value)
				Me.SendPropertyChanging
				Me._lcnno = value
				Me.SendPropertyChanged("lcnno")
				Me.OnlcnnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnsid", DbType:="Int")>  _
	Public Property lcnsid() As System.Nullable(Of Integer)
		Get
			Return Me._lcnsid
		End Get
		Set
			If (Me._lcnsid.Equals(value) = false) Then
				Me.OnlcnsidChanging(value)
				Me.SendPropertyChanging
				Me._lcnsid = value
				Me.SendPropertyChanged("lcnsid")
				Me.OnlcnsidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fdpdtno", DbType:="NVarChar(255)")>  _
	Public Property fdpdtno() As String
		Get
			Return Me._fdpdtno
		End Get
		Set
			If (String.Equals(Me._fdpdtno, value) = false) Then
				Me.OnfdpdtnoChanging(value)
				Me.SendPropertyChanging
				Me._fdpdtno = value
				Me.SendPropertyChanged("fdpdtno")
				Me.OnfdpdtnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcntypecd", DbType:="Int")>  _
	Public Property lcntypecd() As System.Nullable(Of Integer)
		Get
			Return Me._lcntypecd
		End Get
		Set
			If (Me._lcntypecd.Equals(value) = false) Then
				Me.OnlcntypecdChanging(value)
				Me.SendPropertyChanging
				Me._lcntypecd = value
				Me.SendPropertyChanged("lcntypecd")
				Me.OnlcntypecdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_prdnmt", DbType:="NVarChar(MAX)")>  _
	Public Property prdnmt() As String
		Get
			Return Me._prdnmt
		End Get
		Set
			If (String.Equals(Me._prdnmt, value) = false) Then
				Me.OnprdnmtChanging(value)
				Me.SendPropertyChanging
				Me._prdnmt = value
				Me.SendPropertyChanged("prdnmt")
				Me.OnprdnmtChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_prdnme", DbType:="NVarChar(MAX)")>  _
	Public Property prdnme() As String
		Get
			Return Me._prdnme
		End Get
		Set
			If (String.Equals(Me._prdnme, value) = false) Then
				Me.OnprdnmeChanging(value)
				Me.SendPropertyChanging
				Me._prdnme = value
				Me.SendPropertyChanged("prdnme")
				Me.OnprdnmeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Producer_Name", DbType:="NVarChar(MAX)")>  _
	Public Property Producer_Name() As String
		Get
			Return Me._Producer_Name
		End Get
		Set
			If (String.Equals(Me._Producer_Name, value) = false) Then
				Me.OnProducer_NameChanging(value)
				Me.SendPropertyChanging
				Me._Producer_Name = value
				Me.SendPropertyChanged("Producer_Name")
				Me.OnProducer_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_groupname", DbType:="NVarChar(50)")>  _
	Public Property groupname() As String
		Get
			Return Me._groupname
		End Get
		Set
			If (String.Equals(Me._groupname, value) = false) Then
				Me.OngroupnameChanging(value)
				Me.SendPropertyChanging
				Me._groupname = value
				Me.SendPropertyChanged("groupname")
				Me.OngroupnameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NewCode", DbType:="NVarChar(30)")>  _
	Public Property NewCode() As String
		Get
			Return Me._NewCode
		End Get
		Set
			If (String.Equals(Me._NewCode, value) = false) Then
				Me.OnNewCodeChanging(value)
				Me.SendPropertyChanging
				Me._NewCode = value
				Me.SendPropertyChanged("NewCode")
				Me.OnNewCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Ranking", DbType:="NVarChar(50)")>  _
	Public Property Ranking() As String
		Get
			Return Me._Ranking
		End Get
		Set
			If (String.Equals(Me._Ranking, value) = false) Then
				Me.OnRankingChanging(value)
				Me.SendPropertyChanging
				Me._Ranking = value
				Me.SendPropertyChanged("Ranking")
				Me.OnRankingChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cntcd", DbType:="NVarChar(50)")>  _
	Public Property cntcd() As String
		Get
			Return Me._cntcd
		End Get
		Set
			If (String.Equals(Me._cntcd, value) = false) Then
				Me.OncntcdChanging(value)
				Me.SendPropertyChanging
				Me._cntcd = value
				Me.SendPropertyChanged("cntcd")
				Me.OncntcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_appdate", DbType:="NVarChar(MAX)")>  _
	Public Property appdate() As String
		Get
			Return Me._appdate
		End Get
		Set
			If (String.Equals(Me._appdate, value) = false) Then
				Me.OnappdateChanging(value)
				Me.SendPropertyChanging
				Me._appdate = value
				Me.SendPropertyChanged("appdate")
				Me.OnappdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_expdate", DbType:="DateTime")>  _
	Public Property expdate() As System.Nullable(Of Date)
		Get
			Return Me._expdate
		End Get
		Set
			If (Me._expdate.Equals(value) = false) Then
				Me.OnexpdateChanging(value)
				Me.SendPropertyChanging
				Me._expdate = value
				Me.SendPropertyChanged("expdate")
				Me.OnexpdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreateDate", DbType:="DateTime")>  _
	Public Property CreateDate() As System.Nullable(Of Date)
		Get
			Return Me._CreateDate
		End Get
		Set
			If (Me._CreateDate.Equals(value) = false) Then
				Me.OnCreateDateChanging(value)
				Me.SendPropertyChanging
				Me._CreateDate = value
				Me.SendPropertyChanged("CreateDate")
				Me.OnCreateDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UpdateDate", DbType:="DateTime")>  _
	Public Property UpdateDate() As System.Nullable(Of Date)
		Get
			Return Me._UpdateDate
		End Get
		Set
			If (Me._UpdateDate.Equals(value) = false) Then
				Me.OnUpdateDateChanging(value)
				Me.SendPropertyChanging
				Me._UpdateDate = value
				Me.SendPropertyChanged("UpdateDate")
				Me.OnUpdateDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rid", DbType:="Int")>  _
	Public Property rid() As System.Nullable(Of Integer)
		Get
			Return Me._rid
		End Get
		Set
			If (Me._rid.Equals(value) = false) Then
				Me.OnridChanging(value)
				Me.SendPropertyChanging
				Me._rid = value
				Me.SendPropertyChanged("rid")
				Me.OnridChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Cer_expdate", DbType:="DateTime")>  _
	Public Property Cer_expdate() As System.Nullable(Of Date)
		Get
			Return Me._Cer_expdate
		End Get
		Set
			If (Me._Cer_expdate.Equals(value) = false) Then
				Me.OnCer_expdateChanging(value)
				Me.SendPropertyChanging
				Me._Cer_expdate = value
				Me.SendPropertyChanged("Cer_expdate")
				Me.OnCer_expdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Brand", DbType:="NVarChar(MAX)")>  _
	Public Property Brand() As String
		Get
			Return Me._Brand
		End Get
		Set
			If (String.Equals(Me._Brand, value) = false) Then
				Me.OnBrandChanging(value)
				Me.SendPropertyChanging
				Me._Brand = value
				Me.SendPropertyChanged("Brand")
				Me.OnBrandChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thanm", DbType:="NVarChar(MAX)")>  _
	Public Property thanm() As String
		Get
			Return Me._thanm
		End Get
		Set
			If (String.Equals(Me._thanm, value) = false) Then
				Me.OnthanmChanging(value)
				Me.SendPropertyChanging
				Me._thanm = value
				Me.SendPropertyChanged("thanm")
				Me.OnthanmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Status", DbType:="Int")>  _
	Public Property Status() As System.Nullable(Of Integer)
		Get
			Return Me._Status
		End Get
		Set
			If (Me._Status.Equals(value) = false) Then
				Me.OnStatusChanging(value)
				Me.SendPropertyChanging
				Me._Status = value
				Me.SendPropertyChanged("Status")
				Me.OnStatusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Addr", DbType:="NVarChar(MAX)")>  _
	Public Property Addr() As String
		Get
			Return Me._Addr
		End Get
		Set
			If (String.Equals(Me._Addr, value) = false) Then
				Me.OnAddrChanging(value)
				Me.SendPropertyChanging
				Me._Addr = value
				Me.SendPropertyChanged("Addr")
				Me.OnAddrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fdtypecd", DbType:="Int")>  _
	Public Property fdtypecd() As System.Nullable(Of Integer)
		Get
			Return Me._fdtypecd
		End Get
		Set
			If (Me._fdtypecd.Equals(value) = false) Then
				Me.OnfdtypecdChanging(value)
				Me.SendPropertyChanging
				Me._fdtypecd = value
				Me.SendPropertyChanged("fdtypecd")
				Me.OnfdtypecdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fdtypenm", DbType:="NVarChar(MAX)")>  _
	Public Property fdtypenm() As String
		Get
			Return Me._fdtypenm
		End Get
		Set
			If (String.Equals(Me._fdtypenm, value) = false) Then
				Me.OnfdtypenmChanging(value)
				Me.SendPropertyChanging
				Me._fdtypenm = value
				Me.SendPropertyChanged("fdtypenm")
				Me.OnfdtypenmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thanmowner", DbType:="NVarChar(MAX)")>  _
	Public Property thanmowner() As String
		Get
			Return Me._thanmowner
		End Get
		Set
			If (String.Equals(Me._thanmowner, value) = false) Then
				Me.OnthanmownerChanging(value)
				Me.SendPropertyChanging
				Me._thanmowner = value
				Me.SendPropertyChanged("thanmowner")
				Me.OnthanmownerChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EXP", DbType:="NVarChar(MAX)")>  _
	Public Property EXP() As String
		Get
			Return Me._EXP
		End Get
		Set
			If (String.Equals(Me._EXP, value) = false) Then
				Me.OnEXPChanging(value)
				Me.SendPropertyChanging
				Me._EXP = value
				Me.SendPropertyChanged("EXP")
				Me.OnEXPChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctlcnno", DbType:="NVarChar(MAX)")>  _
	Public Property lctlcnno() As String
		Get
			Return Me._lctlcnno
		End Get
		Set
			If (String.Equals(Me._lctlcnno, value) = false) Then
				Me.OnlctlcnnoChanging(value)
				Me.SendPropertyChanging
				Me._lctlcnno = value
				Me.SendPropertyChanged("lctlcnno")
				Me.OnlctlcnnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_AUTHORIZE", DbType:="NVarChar(MAX)")>  _
	Public Property CITIZEN_AUTHORIZE() As String
		Get
			Return Me._CITIZEN_AUTHORIZE
		End Get
		Set
			If (String.Equals(Me._CITIZEN_AUTHORIZE, value) = false) Then
				Me.OnCITIZEN_AUTHORIZEChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_AUTHORIZE = value
				Me.SendPropertyChanged("CITIZEN_AUTHORIZE")
				Me.OnCITIZEN_AUTHORIZEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SUBPDT", DbType:="NVarChar(MAX)")>  _
	Public Property SUBPDT() As String
		Get
			Return Me._SUBPDT
		End Get
		Set
			If (String.Equals(Me._SUBPDT, value) = false) Then
				Me.OnSUBPDTChanging(value)
				Me.SendPropertyChanging
				Me._SUBPDT = value
				Me.SendPropertyChanged("SUBPDT")
				Me.OnSUBPDTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MTHCD", DbType:="NVarChar(MAX)")>  _
	Public Property MTHCD() As String
		Get
			Return Me._MTHCD
		End Get
		Set
			If (String.Equals(Me._MTHCD, value) = false) Then
				Me.OnMTHCDChanging(value)
				Me.SendPropertyChanging
				Me._MTHCD = value
				Me.SendPropertyChanged("MTHCD")
				Me.OnMTHCDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_frgn_addr", DbType:="NVarChar(MAX)")>  _
	Public Property frgn_addr() As String
		Get
			Return Me._frgn_addr
		End Get
		Set
			If (String.Equals(Me._frgn_addr, value) = false) Then
				Me.Onfrgn_addrChanging(value)
				Me.SendPropertyChanging
				Me._frgn_addr = value
				Me.SendPropertyChanged("frgn_addr")
				Me.Onfrgn_addrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCN_STATUS", DbType:="Int")>  _
	Public Property LCN_STATUS() As System.Nullable(Of Integer)
		Get
			Return Me._LCN_STATUS
		End Get
		Set
			If (Me._LCN_STATUS.Equals(value) = false) Then
				Me.OnLCN_STATUSChanging(value)
				Me.SendPropertyChanging
				Me._LCN_STATUS = value
				Me.SendPropertyChanged("LCN_STATUS")
				Me.OnLCN_STATUSChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCN_STATUS_NAME", DbType:="NVarChar(MAX)")>  _
	Public Property LCN_STATUS_NAME() As String
		Get
			Return Me._LCN_STATUS_NAME
		End Get
		Set
			If (String.Equals(Me._LCN_STATUS_NAME, value) = false) Then
				Me.OnLCN_STATUS_NAMEChanging(value)
				Me.SendPropertyChanging
				Me._LCN_STATUS_NAME = value
				Me.SendPropertyChanged("LCN_STATUS_NAME")
				Me.OnLCN_STATUS_NAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FACTORY_TYPE", DbType:="NVarChar(MAX)")>  _
	Public Property FACTORY_TYPE() As String
		Get
			Return Me._FACTORY_TYPE
		End Get
		Set
			If (String.Equals(Me._FACTORY_TYPE, value) = false) Then
				Me.OnFACTORY_TYPEChanging(value)
				Me.SendPropertyChanging
				Me._FACTORY_TYPE = value
				Me.SendPropertyChanged("FACTORY_TYPE")
				Me.OnFACTORY_TYPEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_APPLICTION_TYPE", DbType:="NVarChar(50)")>  _
	Public Property APPLICTION_TYPE() As String
		Get
			Return Me._APPLICTION_TYPE
		End Get
		Set
			If (String.Equals(Me._APPLICTION_TYPE, value) = false) Then
				Me.OnAPPLICTION_TYPEChanging(value)
				Me.SendPropertyChanging
				Me._APPLICTION_TYPE = value
				Me.SendPropertyChanged("APPLICTION_TYPE")
				Me.OnAPPLICTION_TYPEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TAXNO", DbType:="NVarChar(MAX)")>  _
	Public Property TAXNO() As String
		Get
			Return Me._TAXNO
		End Get
		Set
			If (String.Equals(Me._TAXNO, value) = false) Then
				Me.OnTAXNOChanging(value)
				Me.SendPropertyChanging
				Me._TAXNO = value
				Me.SendPropertyChanged("TAXNO")
				Me.OnTAXNOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DOSAGE", DbType:="Float")>  _
	Public Property DOSAGE() As System.Nullable(Of Double)
		Get
			Return Me._DOSAGE
		End Get
		Set
			If (Me._DOSAGE.Equals(value) = false) Then
				Me.OnDOSAGEChanging(value)
				Me.SendPropertyChanging
				Me._DOSAGE = value
				Me.SendPropertyChanged("DOSAGE")
				Me.OnDOSAGEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EXPDAY", DbType:="Int")>  _
	Public Property EXPDAY() As System.Nullable(Of Integer)
		Get
			Return Me._EXPDAY
		End Get
		Set
			If (Me._EXPDAY.Equals(value) = false) Then
				Me.OnEXPDAYChanging(value)
				Me.SendPropertyChanging
				Me._EXPDAY = value
				Me.SendPropertyChanged("EXPDAY")
				Me.OnEXPDAYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SUBPDT_NM", DbType:="NVarChar(MAX)")>  _
	Public Property SUBPDT_NM() As String
		Get
			Return Me._SUBPDT_NM
		End Get
		Set
			If (String.Equals(Me._SUBPDT_NM, value) = false) Then
				Me.OnSUBPDT_NMChanging(value)
				Me.SendPropertyChanging
				Me._SUBPDT_NM = value
				Me.SendPropertyChanged("SUBPDT_NM")
				Me.OnSUBPDT_NMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MTHCD_NM", DbType:="NVarChar(MAX)")>  _
	Public Property MTHCD_NM() As String
		Get
			Return Me._MTHCD_NM
		End Get
		Set
			If (String.Equals(Me._MTHCD_NM, value) = false) Then
				Me.OnMTHCD_NMChanging(value)
				Me.SendPropertyChanging
				Me._MTHCD_NM = value
				Me.SendPropertyChanged("MTHCD_NM")
				Me.OnMTHCD_NMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVE", DbType:="Int")>  _
	Public Property ACTIVE() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVE
		End Get
		Set
			If (Me._ACTIVE.Equals(value) = false) Then
				Me.OnACTIVEChanging(value)
				Me.SendPropertyChanging
				Me._ACTIVE = value
				Me.SendPropertyChanged("ACTIVE")
				Me.OnACTIVEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FML", DbType:="Int")>  _
	Public Property FML() As System.Nullable(Of Integer)
		Get
			Return Me._FML
		End Get
		Set
			If (Me._FML.Equals(value) = false) Then
				Me.OnFMLChanging(value)
				Me.SendPropertyChanging
				Me._FML = value
				Me.SendPropertyChanged("FML")
				Me.OnFMLChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_status_name", DbType:="NVarChar(MAX)")>  _
	Public Property status_name() As String
		Get
			Return Me._status_name
		End Get
		Set
			If (String.Equals(Me._status_name, value) = false) Then
				Me.Onstatus_nameChanging(value)
				Me.SendPropertyChanging
				Me._status_name = value
				Me.SendPropertyChanged("status_name")
				Me.Onstatus_nameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_remark_product", DbType:="NVarChar(MAX)")>  _
	Public Property remark_product() As String
		Get
			Return Me._remark_product
		End Get
		Set
			If (String.Equals(Me._remark_product, value) = false) Then
				Me.Onremark_productChanging(value)
				Me.SendPropertyChanging
				Me._remark_product = value
				Me.SendPropertyChanged("remark_product")
				Me.Onremark_productChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_remark_location", DbType:="NVarChar(MAX)")>  _
	Public Property remark_location() As String
		Get
			Return Me._remark_location
		End Get
		Set
			If (String.Equals(Me._remark_location, value) = false) Then
				Me.Onremark_locationChanging(value)
				Me.SendPropertyChanging
				Me._remark_location = value
				Me.SendPropertyChanged("remark_location")
				Me.Onremark_locationChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CANCEL_DATE", DbType:="DateTime")>  _
	Public Property CANCEL_DATE() As System.Nullable(Of Date)
		Get
			Return Me._CANCEL_DATE
		End Get
		Set
			If (Me._CANCEL_DATE.Equals(value) = false) Then
				Me.OnCANCEL_DATEChanging(value)
				Me.SendPropertyChanging
				Me._CANCEL_DATE = value
				Me.SendPropertyChanged("CANCEL_DATE")
				Me.OnCANCEL_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_APPROVE_DATE", DbType:="Date")>  _
	Public Property APPROVE_DATE() As System.Nullable(Of Date)
		Get
			Return Me._APPROVE_DATE
		End Get
		Set
			If (Me._APPROVE_DATE.Equals(value) = false) Then
				Me.OnAPPROVE_DATEChanging(value)
				Me.SendPropertyChanging
				Me._APPROVE_DATE = value
				Me.SendPropertyChanged("APPROVE_DATE")
				Me.OnAPPROVE_DATEChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tb_log_temp_food")>  _
Partial Public Class tb_log_temp_food
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDA As Integer
	
	Private _IDENTIFY_EDIT As String
	
	Private _remark As String
	
	Private _system As String
	
	Private _fdpdtno As String
	
	Private _log_des As String
	
	Private _log_date As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnIDENTIFY_EDITChanging(value As String)
    End Sub
    Partial Private Sub OnIDENTIFY_EDITChanged()
    End Sub
    Partial Private Sub OnremarkChanging(value As String)
    End Sub
    Partial Private Sub OnremarkChanged()
    End Sub
    Partial Private Sub OnsystemChanging(value As String)
    End Sub
    Partial Private Sub OnsystemChanged()
    End Sub
    Partial Private Sub OnfdpdtnoChanging(value As String)
    End Sub
    Partial Private Sub OnfdpdtnoChanged()
    End Sub
    Partial Private Sub Onlog_desChanging(value As String)
    End Sub
    Partial Private Sub Onlog_desChanged()
    End Sub
    Partial Private Sub Onlog_dateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub Onlog_dateChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDENTIFY_EDIT", DbType:="NVarChar(50)")>  _
	Public Property IDENTIFY_EDIT() As String
		Get
			Return Me._IDENTIFY_EDIT
		End Get
		Set
			If (String.Equals(Me._IDENTIFY_EDIT, value) = false) Then
				Me.OnIDENTIFY_EDITChanging(value)
				Me.SendPropertyChanging
				Me._IDENTIFY_EDIT = value
				Me.SendPropertyChanged("IDENTIFY_EDIT")
				Me.OnIDENTIFY_EDITChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_remark", DbType:="NVarChar(MAX)")>  _
	Public Property remark() As String
		Get
			Return Me._remark
		End Get
		Set
			If (String.Equals(Me._remark, value) = false) Then
				Me.OnremarkChanging(value)
				Me.SendPropertyChanging
				Me._remark = value
				Me.SendPropertyChanged("remark")
				Me.OnremarkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_system", DbType:="NVarChar(MAX)")>  _
	Public Property system() As String
		Get
			Return Me._system
		End Get
		Set
			If (String.Equals(Me._system, value) = false) Then
				Me.OnsystemChanging(value)
				Me.SendPropertyChanging
				Me._system = value
				Me.SendPropertyChanged("system")
				Me.OnsystemChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fdpdtno", DbType:="NVarChar(50)")>  _
	Public Property fdpdtno() As String
		Get
			Return Me._fdpdtno
		End Get
		Set
			If (String.Equals(Me._fdpdtno, value) = false) Then
				Me.OnfdpdtnoChanging(value)
				Me.SendPropertyChanging
				Me._fdpdtno = value
				Me.SendPropertyChanged("fdpdtno")
				Me.OnfdpdtnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_log_des", DbType:="NVarChar(MAX)")>  _
	Public Property log_des() As String
		Get
			Return Me._log_des
		End Get
		Set
			If (String.Equals(Me._log_des, value) = false) Then
				Me.Onlog_desChanging(value)
				Me.SendPropertyChanging
				Me._log_des = value
				Me.SendPropertyChanged("log_des")
				Me.Onlog_desChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_log_date", DbType:="DateTime")>  _
	Public Property log_date() As System.Nullable(Of Date)
		Get
			Return Me._log_date
		End Get
		Set
			If (Me._log_date.Equals(value) = false) Then
				Me.Onlog_dateChanging(value)
				Me.SendPropertyChanging
				Me._log_date = value
				Me.SendPropertyChanged("log_date")
				Me.Onlog_dateChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
