'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="FDA_XML_TXC")>  _
Partial Public Class LGT_XML_TXCDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertXML_TXC1(instance As XML_TXC1)
    End Sub
  Partial Private Sub UpdateXML_TXC1(instance As XML_TXC1)
    End Sub
  Partial Private Sub DeleteXML_TXC1(instance As XML_TXC1)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("FDA_XML_TXCConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property XML_TXC1s() As System.Data.Linq.Table(Of XML_TXC1)
		Get
			Return Me.GetTable(Of XML_TXC1)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.XML_TXC")>  _
Partial Public Class XML_TXC1
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDA As Integer
	
	Private _pvncd As String
	
	Private _infno As String
	
	Private _rgno As String
	
	Private _lcnsid As String
	
	Private _lcntpcd As String
	
	Private _rcvdate As String
	
	Private _expdate As String
	
	Private _ttrdnm As String
	
	Private _etrdnm As String
	
	Private _fpdnm As String
	
	Private _cntcd As String
	
	Private _rid As String
	
	Private _GrouNAME As String
	
	Private _Newcode As String
	
	Private _Ranking As String
	
	Private _lctcd As String
	
	Private _lctnmcd As String
	
	Private _CITIZEN_ID As String
	
	Private _FULL_ADDR As String
	
	Private _lct_name As String
	
	Private _owner_name As String
	
	Private _LCN_DISPLAY As String
	
	Private _LCN_SEARCH As String
	
	Private _IDENTIFY As String
	
	Private _LCN_SEARCH2 As String
	
	Private _STATUS_ID As System.Nullable(Of Integer)
	
	Private _STATUS_NAME As String
	
	Private _LICENSE_TYPE_NAME As String
	
	Private _LCNTPCD_NAME As String
	
	Private _rcvno As String
	
	Private _abbreviation As String
	
	Private _register_abbreviation As String
	
	Private _register As String
	
	Private _register_cwabbr As String
	
	Private _rgtpnm As String
	
	Private _rstnm As String
	
	Private _rstcd As String
	
	Private _psntp As String
	
	Private _cnclnm As String
	
	Private _usedcd As String
	
	Private _frmtcd As String
	
	Private _usednm As String
	
	Private _frmtnm As String
	
	Private _chngwtcd As String
	
	Private _thachngwtnm As String
	
	Private _rcvdate_TH As String
	
	Private _rgdate As String
	
	Private _rgdate_TH As String
	
	Private _expdate_TH As String
	
	Private _isocode As String
	
	Private _engcntnm As String
	
	Private _thacntnm As String
	
	Private _Newcode_R As String
	
	Private _lmdfdate As String
	
	Private _qty As String
	
	Private _unitnm As String
	
	Private _lctnm_keep As String
	
	Private _address_keep As String
	
	Private _chngwtcd_ask_where As String
	
	Private _ask_where As String
	
	Private _register_lcnno As String
	
	Private _cnsdcd As String
	
	Private _lcntpnm As String
	
	Private _thanm_manufacture As String
	
	Private _thanm_addr_manufacture As String
	
	Private _action_notice As String
	
	Private _stunit As String
	
	Private _Newcode_contro As String
	
	Private _rcvdate_EN As String
	
	Private _export_nm As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnpvncdChanging(value As String)
    End Sub
    Partial Private Sub OnpvncdChanged()
    End Sub
    Partial Private Sub OninfnoChanging(value As String)
    End Sub
    Partial Private Sub OninfnoChanged()
    End Sub
    Partial Private Sub OnrgnoChanging(value As String)
    End Sub
    Partial Private Sub OnrgnoChanged()
    End Sub
    Partial Private Sub OnlcnsidChanging(value As String)
    End Sub
    Partial Private Sub OnlcnsidChanged()
    End Sub
    Partial Private Sub OnlcntpcdChanging(value As String)
    End Sub
    Partial Private Sub OnlcntpcdChanged()
    End Sub
    Partial Private Sub OnrcvdateChanging(value As String)
    End Sub
    Partial Private Sub OnrcvdateChanged()
    End Sub
    Partial Private Sub OnexpdateChanging(value As String)
    End Sub
    Partial Private Sub OnexpdateChanged()
    End Sub
    Partial Private Sub OnttrdnmChanging(value As String)
    End Sub
    Partial Private Sub OnttrdnmChanged()
    End Sub
    Partial Private Sub OnetrdnmChanging(value As String)
    End Sub
    Partial Private Sub OnetrdnmChanged()
    End Sub
    Partial Private Sub OnfpdnmChanging(value As String)
    End Sub
    Partial Private Sub OnfpdnmChanged()
    End Sub
    Partial Private Sub OncntcdChanging(value As String)
    End Sub
    Partial Private Sub OncntcdChanged()
    End Sub
    Partial Private Sub OnridChanging(value As String)
    End Sub
    Partial Private Sub OnridChanged()
    End Sub
    Partial Private Sub OnGrouNAMEChanging(value As String)
    End Sub
    Partial Private Sub OnGrouNAMEChanged()
    End Sub
    Partial Private Sub OnNewcodeChanging(value As String)
    End Sub
    Partial Private Sub OnNewcodeChanged()
    End Sub
    Partial Private Sub OnRankingChanging(value As String)
    End Sub
    Partial Private Sub OnRankingChanged()
    End Sub
    Partial Private Sub OnlctcdChanging(value As String)
    End Sub
    Partial Private Sub OnlctcdChanged()
    End Sub
    Partial Private Sub OnlctnmcdChanging(value As String)
    End Sub
    Partial Private Sub OnlctnmcdChanged()
    End Sub
    Partial Private Sub OnCITIZEN_IDChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_IDChanged()
    End Sub
    Partial Private Sub OnFULL_ADDRChanging(value As String)
    End Sub
    Partial Private Sub OnFULL_ADDRChanged()
    End Sub
    Partial Private Sub Onlct_nameChanging(value As String)
    End Sub
    Partial Private Sub Onlct_nameChanged()
    End Sub
    Partial Private Sub Onowner_nameChanging(value As String)
    End Sub
    Partial Private Sub Onowner_nameChanged()
    End Sub
    Partial Private Sub OnLCN_DISPLAYChanging(value As String)
    End Sub
    Partial Private Sub OnLCN_DISPLAYChanged()
    End Sub
    Partial Private Sub OnLCN_SEARCHChanging(value As String)
    End Sub
    Partial Private Sub OnLCN_SEARCHChanged()
    End Sub
    Partial Private Sub OnIDENTIFYChanging(value As String)
    End Sub
    Partial Private Sub OnIDENTIFYChanged()
    End Sub
    Partial Private Sub OnLCN_SEARCH2Changing(value As String)
    End Sub
    Partial Private Sub OnLCN_SEARCH2Changed()
    End Sub
    Partial Private Sub OnSTATUS_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSTATUS_IDChanged()
    End Sub
    Partial Private Sub OnSTATUS_NAMEChanging(value As String)
    End Sub
    Partial Private Sub OnSTATUS_NAMEChanged()
    End Sub
    Partial Private Sub OnLICENSE_TYPE_NAMEChanging(value As String)
    End Sub
    Partial Private Sub OnLICENSE_TYPE_NAMEChanged()
    End Sub
    Partial Private Sub OnLCNTPCD_NAMEChanging(value As String)
    End Sub
    Partial Private Sub OnLCNTPCD_NAMEChanged()
    End Sub
    Partial Private Sub OnrcvnoChanging(value As String)
    End Sub
    Partial Private Sub OnrcvnoChanged()
    End Sub
    Partial Private Sub OnabbreviationChanging(value As String)
    End Sub
    Partial Private Sub OnabbreviationChanged()
    End Sub
    Partial Private Sub Onregister_abbreviationChanging(value As String)
    End Sub
    Partial Private Sub Onregister_abbreviationChanged()
    End Sub
    Partial Private Sub OnregisterChanging(value As String)
    End Sub
    Partial Private Sub OnregisterChanged()
    End Sub
    Partial Private Sub Onregister_cwabbrChanging(value As String)
    End Sub
    Partial Private Sub Onregister_cwabbrChanged()
    End Sub
    Partial Private Sub OnrgtpnmChanging(value As String)
    End Sub
    Partial Private Sub OnrgtpnmChanged()
    End Sub
    Partial Private Sub OnrstnmChanging(value As String)
    End Sub
    Partial Private Sub OnrstnmChanged()
    End Sub
    Partial Private Sub OnrstcdChanging(value As String)
    End Sub
    Partial Private Sub OnrstcdChanged()
    End Sub
    Partial Private Sub OnpsntpChanging(value As String)
    End Sub
    Partial Private Sub OnpsntpChanged()
    End Sub
    Partial Private Sub OncnclnmChanging(value As String)
    End Sub
    Partial Private Sub OncnclnmChanged()
    End Sub
    Partial Private Sub OnusedcdChanging(value As String)
    End Sub
    Partial Private Sub OnusedcdChanged()
    End Sub
    Partial Private Sub OnfrmtcdChanging(value As String)
    End Sub
    Partial Private Sub OnfrmtcdChanged()
    End Sub
    Partial Private Sub OnusednmChanging(value As String)
    End Sub
    Partial Private Sub OnusednmChanged()
    End Sub
    Partial Private Sub OnfrmtnmChanging(value As String)
    End Sub
    Partial Private Sub OnfrmtnmChanged()
    End Sub
    Partial Private Sub OnchngwtcdChanging(value As String)
    End Sub
    Partial Private Sub OnchngwtcdChanged()
    End Sub
    Partial Private Sub OnthachngwtnmChanging(value As String)
    End Sub
    Partial Private Sub OnthachngwtnmChanged()
    End Sub
    Partial Private Sub Onrcvdate_THChanging(value As String)
    End Sub
    Partial Private Sub Onrcvdate_THChanged()
    End Sub
    Partial Private Sub OnrgdateChanging(value As String)
    End Sub
    Partial Private Sub OnrgdateChanged()
    End Sub
    Partial Private Sub Onrgdate_THChanging(value As String)
    End Sub
    Partial Private Sub Onrgdate_THChanged()
    End Sub
    Partial Private Sub Onexpdate_THChanging(value As String)
    End Sub
    Partial Private Sub Onexpdate_THChanged()
    End Sub
    Partial Private Sub OnisocodeChanging(value As String)
    End Sub
    Partial Private Sub OnisocodeChanged()
    End Sub
    Partial Private Sub OnengcntnmChanging(value As String)
    End Sub
    Partial Private Sub OnengcntnmChanged()
    End Sub
    Partial Private Sub OnthacntnmChanging(value As String)
    End Sub
    Partial Private Sub OnthacntnmChanged()
    End Sub
    Partial Private Sub OnNewcode_RChanging(value As String)
    End Sub
    Partial Private Sub OnNewcode_RChanged()
    End Sub
    Partial Private Sub OnlmdfdateChanging(value As String)
    End Sub
    Partial Private Sub OnlmdfdateChanged()
    End Sub
    Partial Private Sub OnqtyChanging(value As String)
    End Sub
    Partial Private Sub OnqtyChanged()
    End Sub
    Partial Private Sub OnunitnmChanging(value As String)
    End Sub
    Partial Private Sub OnunitnmChanged()
    End Sub
    Partial Private Sub Onlctnm_keepChanging(value As String)
    End Sub
    Partial Private Sub Onlctnm_keepChanged()
    End Sub
    Partial Private Sub Onaddress_keepChanging(value As String)
    End Sub
    Partial Private Sub Onaddress_keepChanged()
    End Sub
    Partial Private Sub Onchngwtcd_ask_whereChanging(value As String)
    End Sub
    Partial Private Sub Onchngwtcd_ask_whereChanged()
    End Sub
    Partial Private Sub Onask_whereChanging(value As String)
    End Sub
    Partial Private Sub Onask_whereChanged()
    End Sub
    Partial Private Sub Onregister_lcnnoChanging(value As String)
    End Sub
    Partial Private Sub Onregister_lcnnoChanged()
    End Sub
    Partial Private Sub OncnsdcdChanging(value As String)
    End Sub
    Partial Private Sub OncnsdcdChanged()
    End Sub
    Partial Private Sub OnlcntpnmChanging(value As String)
    End Sub
    Partial Private Sub OnlcntpnmChanged()
    End Sub
    Partial Private Sub Onthanm_manufactureChanging(value As String)
    End Sub
    Partial Private Sub Onthanm_manufactureChanged()
    End Sub
    Partial Private Sub Onthanm_addr_manufactureChanging(value As String)
    End Sub
    Partial Private Sub Onthanm_addr_manufactureChanged()
    End Sub
    Partial Private Sub Onaction_noticeChanging(value As String)
    End Sub
    Partial Private Sub Onaction_noticeChanged()
    End Sub
    Partial Private Sub OnstunitChanging(value As String)
    End Sub
    Partial Private Sub OnstunitChanged()
    End Sub
    Partial Private Sub OnNewcode_controChanging(value As String)
    End Sub
    Partial Private Sub OnNewcode_controChanged()
    End Sub
    Partial Private Sub Onrcvdate_ENChanging(value As String)
    End Sub
    Partial Private Sub Onrcvdate_ENChanged()
    End Sub
    Partial Private Sub Onexport_nmChanging(value As String)
    End Sub
    Partial Private Sub Onexport_nmChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pvncd", DbType:="NVarChar(50)")>  _
	Public Property pvncd() As String
		Get
			Return Me._pvncd
		End Get
		Set
			If (String.Equals(Me._pvncd, value) = false) Then
				Me.OnpvncdChanging(value)
				Me.SendPropertyChanging
				Me._pvncd = value
				Me.SendPropertyChanged("pvncd")
				Me.OnpvncdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_infno", DbType:="NVarChar(50)")>  _
	Public Property infno() As String
		Get
			Return Me._infno
		End Get
		Set
			If (String.Equals(Me._infno, value) = false) Then
				Me.OninfnoChanging(value)
				Me.SendPropertyChanging
				Me._infno = value
				Me.SendPropertyChanged("infno")
				Me.OninfnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rgno", DbType:="NVarChar(MAX)")>  _
	Public Property rgno() As String
		Get
			Return Me._rgno
		End Get
		Set
			If (String.Equals(Me._rgno, value) = false) Then
				Me.OnrgnoChanging(value)
				Me.SendPropertyChanging
				Me._rgno = value
				Me.SendPropertyChanged("rgno")
				Me.OnrgnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnsid", DbType:="NVarChar(50)")>  _
	Public Property lcnsid() As String
		Get
			Return Me._lcnsid
		End Get
		Set
			If (String.Equals(Me._lcnsid, value) = false) Then
				Me.OnlcnsidChanging(value)
				Me.SendPropertyChanging
				Me._lcnsid = value
				Me.SendPropertyChanged("lcnsid")
				Me.OnlcnsidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcntpcd", DbType:="NVarChar(50)")>  _
	Public Property lcntpcd() As String
		Get
			Return Me._lcntpcd
		End Get
		Set
			If (String.Equals(Me._lcntpcd, value) = false) Then
				Me.OnlcntpcdChanging(value)
				Me.SendPropertyChanging
				Me._lcntpcd = value
				Me.SendPropertyChanged("lcntpcd")
				Me.OnlcntpcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rcvdate", DbType:="NVarChar(50)")>  _
	Public Property rcvdate() As String
		Get
			Return Me._rcvdate
		End Get
		Set
			If (String.Equals(Me._rcvdate, value) = false) Then
				Me.OnrcvdateChanging(value)
				Me.SendPropertyChanging
				Me._rcvdate = value
				Me.SendPropertyChanged("rcvdate")
				Me.OnrcvdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_expdate", DbType:="NVarChar(MAX)")>  _
	Public Property expdate() As String
		Get
			Return Me._expdate
		End Get
		Set
			If (String.Equals(Me._expdate, value) = false) Then
				Me.OnexpdateChanging(value)
				Me.SendPropertyChanging
				Me._expdate = value
				Me.SendPropertyChanged("expdate")
				Me.OnexpdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ttrdnm", DbType:="NVarChar(MAX)")>  _
	Public Property ttrdnm() As String
		Get
			Return Me._ttrdnm
		End Get
		Set
			If (String.Equals(Me._ttrdnm, value) = false) Then
				Me.OnttrdnmChanging(value)
				Me.SendPropertyChanging
				Me._ttrdnm = value
				Me.SendPropertyChanged("ttrdnm")
				Me.OnttrdnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_etrdnm", DbType:="NVarChar(MAX)")>  _
	Public Property etrdnm() As String
		Get
			Return Me._etrdnm
		End Get
		Set
			If (String.Equals(Me._etrdnm, value) = false) Then
				Me.OnetrdnmChanging(value)
				Me.SendPropertyChanging
				Me._etrdnm = value
				Me.SendPropertyChanged("etrdnm")
				Me.OnetrdnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fpdnm", DbType:="NVarChar(MAX)")>  _
	Public Property fpdnm() As String
		Get
			Return Me._fpdnm
		End Get
		Set
			If (String.Equals(Me._fpdnm, value) = false) Then
				Me.OnfpdnmChanging(value)
				Me.SendPropertyChanging
				Me._fpdnm = value
				Me.SendPropertyChanged("fpdnm")
				Me.OnfpdnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cntcd", DbType:="NVarChar(MAX)")>  _
	Public Property cntcd() As String
		Get
			Return Me._cntcd
		End Get
		Set
			If (String.Equals(Me._cntcd, value) = false) Then
				Me.OncntcdChanging(value)
				Me.SendPropertyChanging
				Me._cntcd = value
				Me.SendPropertyChanged("cntcd")
				Me.OncntcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rid", DbType:="NChar(10)")>  _
	Public Property rid() As String
		Get
			Return Me._rid
		End Get
		Set
			If (String.Equals(Me._rid, value) = false) Then
				Me.OnridChanging(value)
				Me.SendPropertyChanging
				Me._rid = value
				Me.SendPropertyChanged("rid")
				Me.OnridChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GrouNAME", DbType:="NVarChar(MAX)")>  _
	Public Property GrouNAME() As String
		Get
			Return Me._GrouNAME
		End Get
		Set
			If (String.Equals(Me._GrouNAME, value) = false) Then
				Me.OnGrouNAMEChanging(value)
				Me.SendPropertyChanging
				Me._GrouNAME = value
				Me.SendPropertyChanged("GrouNAME")
				Me.OnGrouNAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Newcode", DbType:="NVarChar(MAX)")>  _
	Public Property Newcode() As String
		Get
			Return Me._Newcode
		End Get
		Set
			If (String.Equals(Me._Newcode, value) = false) Then
				Me.OnNewcodeChanging(value)
				Me.SendPropertyChanging
				Me._Newcode = value
				Me.SendPropertyChanged("Newcode")
				Me.OnNewcodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Ranking", DbType:="NChar(10)")>  _
	Public Property Ranking() As String
		Get
			Return Me._Ranking
		End Get
		Set
			If (String.Equals(Me._Ranking, value) = false) Then
				Me.OnRankingChanging(value)
				Me.SendPropertyChanging
				Me._Ranking = value
				Me.SendPropertyChanged("Ranking")
				Me.OnRankingChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctcd", DbType:="NChar(10)")>  _
	Public Property lctcd() As String
		Get
			Return Me._lctcd
		End Get
		Set
			If (String.Equals(Me._lctcd, value) = false) Then
				Me.OnlctcdChanging(value)
				Me.SendPropertyChanging
				Me._lctcd = value
				Me.SendPropertyChanged("lctcd")
				Me.OnlctcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctnmcd", DbType:="NChar(10)")>  _
	Public Property lctnmcd() As String
		Get
			Return Me._lctnmcd
		End Get
		Set
			If (String.Equals(Me._lctnmcd, value) = false) Then
				Me.OnlctnmcdChanging(value)
				Me.SendPropertyChanging
				Me._lctnmcd = value
				Me.SendPropertyChanged("lctnmcd")
				Me.OnlctnmcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_ID", DbType:="NChar(10)")>  _
	Public Property CITIZEN_ID() As String
		Get
			Return Me._CITIZEN_ID
		End Get
		Set
			If (String.Equals(Me._CITIZEN_ID, value) = false) Then
				Me.OnCITIZEN_IDChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_ID = value
				Me.SendPropertyChanged("CITIZEN_ID")
				Me.OnCITIZEN_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FULL_ADDR", DbType:="NVarChar(MAX)")>  _
	Public Property FULL_ADDR() As String
		Get
			Return Me._FULL_ADDR
		End Get
		Set
			If (String.Equals(Me._FULL_ADDR, value) = false) Then
				Me.OnFULL_ADDRChanging(value)
				Me.SendPropertyChanging
				Me._FULL_ADDR = value
				Me.SendPropertyChanged("FULL_ADDR")
				Me.OnFULL_ADDRChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lct_name", DbType:="NVarChar(MAX)")>  _
	Public Property lct_name() As String
		Get
			Return Me._lct_name
		End Get
		Set
			If (String.Equals(Me._lct_name, value) = false) Then
				Me.Onlct_nameChanging(value)
				Me.SendPropertyChanging
				Me._lct_name = value
				Me.SendPropertyChanged("lct_name")
				Me.Onlct_nameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_owner_name", DbType:="NVarChar(MAX)")>  _
	Public Property owner_name() As String
		Get
			Return Me._owner_name
		End Get
		Set
			If (String.Equals(Me._owner_name, value) = false) Then
				Me.Onowner_nameChanging(value)
				Me.SendPropertyChanging
				Me._owner_name = value
				Me.SendPropertyChanged("owner_name")
				Me.Onowner_nameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCN_DISPLAY", DbType:="NVarChar(MAX)")>  _
	Public Property LCN_DISPLAY() As String
		Get
			Return Me._LCN_DISPLAY
		End Get
		Set
			If (String.Equals(Me._LCN_DISPLAY, value) = false) Then
				Me.OnLCN_DISPLAYChanging(value)
				Me.SendPropertyChanging
				Me._LCN_DISPLAY = value
				Me.SendPropertyChanged("LCN_DISPLAY")
				Me.OnLCN_DISPLAYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCN_SEARCH", DbType:="NVarChar(MAX)")>  _
	Public Property LCN_SEARCH() As String
		Get
			Return Me._LCN_SEARCH
		End Get
		Set
			If (String.Equals(Me._LCN_SEARCH, value) = false) Then
				Me.OnLCN_SEARCHChanging(value)
				Me.SendPropertyChanging
				Me._LCN_SEARCH = value
				Me.SendPropertyChanged("LCN_SEARCH")
				Me.OnLCN_SEARCHChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDENTIFY", DbType:="NVarChar(MAX)")>  _
	Public Property IDENTIFY() As String
		Get
			Return Me._IDENTIFY
		End Get
		Set
			If (String.Equals(Me._IDENTIFY, value) = false) Then
				Me.OnIDENTIFYChanging(value)
				Me.SendPropertyChanging
				Me._IDENTIFY = value
				Me.SendPropertyChanged("IDENTIFY")
				Me.OnIDENTIFYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCN_SEARCH2", DbType:="NVarChar(MAX)")>  _
	Public Property LCN_SEARCH2() As String
		Get
			Return Me._LCN_SEARCH2
		End Get
		Set
			If (String.Equals(Me._LCN_SEARCH2, value) = false) Then
				Me.OnLCN_SEARCH2Changing(value)
				Me.SendPropertyChanging
				Me._LCN_SEARCH2 = value
				Me.SendPropertyChanged("LCN_SEARCH2")
				Me.OnLCN_SEARCH2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STATUS_ID", DbType:="Int")>  _
	Public Property STATUS_ID() As System.Nullable(Of Integer)
		Get
			Return Me._STATUS_ID
		End Get
		Set
			If (Me._STATUS_ID.Equals(value) = false) Then
				Me.OnSTATUS_IDChanging(value)
				Me.SendPropertyChanging
				Me._STATUS_ID = value
				Me.SendPropertyChanged("STATUS_ID")
				Me.OnSTATUS_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STATUS_NAME", DbType:="NVarChar(MAX)")>  _
	Public Property STATUS_NAME() As String
		Get
			Return Me._STATUS_NAME
		End Get
		Set
			If (String.Equals(Me._STATUS_NAME, value) = false) Then
				Me.OnSTATUS_NAMEChanging(value)
				Me.SendPropertyChanging
				Me._STATUS_NAME = value
				Me.SendPropertyChanged("STATUS_NAME")
				Me.OnSTATUS_NAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LICENSE_TYPE_NAME", DbType:="NVarChar(MAX)")>  _
	Public Property LICENSE_TYPE_NAME() As String
		Get
			Return Me._LICENSE_TYPE_NAME
		End Get
		Set
			If (String.Equals(Me._LICENSE_TYPE_NAME, value) = false) Then
				Me.OnLICENSE_TYPE_NAMEChanging(value)
				Me.SendPropertyChanging
				Me._LICENSE_TYPE_NAME = value
				Me.SendPropertyChanged("LICENSE_TYPE_NAME")
				Me.OnLICENSE_TYPE_NAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCNTPCD_NAME", DbType:="NVarChar(MAX)")>  _
	Public Property LCNTPCD_NAME() As String
		Get
			Return Me._LCNTPCD_NAME
		End Get
		Set
			If (String.Equals(Me._LCNTPCD_NAME, value) = false) Then
				Me.OnLCNTPCD_NAMEChanging(value)
				Me.SendPropertyChanging
				Me._LCNTPCD_NAME = value
				Me.SendPropertyChanged("LCNTPCD_NAME")
				Me.OnLCNTPCD_NAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rcvno", DbType:="NVarChar(50)")>  _
	Public Property rcvno() As String
		Get
			Return Me._rcvno
		End Get
		Set
			If (String.Equals(Me._rcvno, value) = false) Then
				Me.OnrcvnoChanging(value)
				Me.SendPropertyChanging
				Me._rcvno = value
				Me.SendPropertyChanged("rcvno")
				Me.OnrcvnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_abbreviation", DbType:="NVarChar(MAX)")>  _
	Public Property abbreviation() As String
		Get
			Return Me._abbreviation
		End Get
		Set
			If (String.Equals(Me._abbreviation, value) = false) Then
				Me.OnabbreviationChanging(value)
				Me.SendPropertyChanging
				Me._abbreviation = value
				Me.SendPropertyChanged("abbreviation")
				Me.OnabbreviationChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_register_abbreviation", DbType:="NVarChar(MAX)")>  _
	Public Property register_abbreviation() As String
		Get
			Return Me._register_abbreviation
		End Get
		Set
			If (String.Equals(Me._register_abbreviation, value) = false) Then
				Me.Onregister_abbreviationChanging(value)
				Me.SendPropertyChanging
				Me._register_abbreviation = value
				Me.SendPropertyChanged("register_abbreviation")
				Me.Onregister_abbreviationChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_register", DbType:="NVarChar(MAX)")>  _
	Public Property register() As String
		Get
			Return Me._register
		End Get
		Set
			If (String.Equals(Me._register, value) = false) Then
				Me.OnregisterChanging(value)
				Me.SendPropertyChanging
				Me._register = value
				Me.SendPropertyChanged("register")
				Me.OnregisterChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_register_cwabbr", DbType:="NVarChar(MAX)")>  _
	Public Property register_cwabbr() As String
		Get
			Return Me._register_cwabbr
		End Get
		Set
			If (String.Equals(Me._register_cwabbr, value) = false) Then
				Me.Onregister_cwabbrChanging(value)
				Me.SendPropertyChanging
				Me._register_cwabbr = value
				Me.SendPropertyChanged("register_cwabbr")
				Me.Onregister_cwabbrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rgtpnm", DbType:="NVarChar(MAX)")>  _
	Public Property rgtpnm() As String
		Get
			Return Me._rgtpnm
		End Get
		Set
			If (String.Equals(Me._rgtpnm, value) = false) Then
				Me.OnrgtpnmChanging(value)
				Me.SendPropertyChanging
				Me._rgtpnm = value
				Me.SendPropertyChanged("rgtpnm")
				Me.OnrgtpnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rstnm", DbType:="NVarChar(MAX)")>  _
	Public Property rstnm() As String
		Get
			Return Me._rstnm
		End Get
		Set
			If (String.Equals(Me._rstnm, value) = false) Then
				Me.OnrstnmChanging(value)
				Me.SendPropertyChanging
				Me._rstnm = value
				Me.SendPropertyChanged("rstnm")
				Me.OnrstnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rstcd", DbType:="NVarChar(MAX)")>  _
	Public Property rstcd() As String
		Get
			Return Me._rstcd
		End Get
		Set
			If (String.Equals(Me._rstcd, value) = false) Then
				Me.OnrstcdChanging(value)
				Me.SendPropertyChanging
				Me._rstcd = value
				Me.SendPropertyChanged("rstcd")
				Me.OnrstcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_psntp", DbType:="NVarChar(MAX)")>  _
	Public Property psntp() As String
		Get
			Return Me._psntp
		End Get
		Set
			If (String.Equals(Me._psntp, value) = false) Then
				Me.OnpsntpChanging(value)
				Me.SendPropertyChanging
				Me._psntp = value
				Me.SendPropertyChanged("psntp")
				Me.OnpsntpChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cnclnm", DbType:="NVarChar(MAX)")>  _
	Public Property cnclnm() As String
		Get
			Return Me._cnclnm
		End Get
		Set
			If (String.Equals(Me._cnclnm, value) = false) Then
				Me.OncnclnmChanging(value)
				Me.SendPropertyChanging
				Me._cnclnm = value
				Me.SendPropertyChanged("cnclnm")
				Me.OncnclnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_usedcd", DbType:="NVarChar(MAX)")>  _
	Public Property usedcd() As String
		Get
			Return Me._usedcd
		End Get
		Set
			If (String.Equals(Me._usedcd, value) = false) Then
				Me.OnusedcdChanging(value)
				Me.SendPropertyChanging
				Me._usedcd = value
				Me.SendPropertyChanged("usedcd")
				Me.OnusedcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_frmtcd", DbType:="NVarChar(MAX)")>  _
	Public Property frmtcd() As String
		Get
			Return Me._frmtcd
		End Get
		Set
			If (String.Equals(Me._frmtcd, value) = false) Then
				Me.OnfrmtcdChanging(value)
				Me.SendPropertyChanging
				Me._frmtcd = value
				Me.SendPropertyChanged("frmtcd")
				Me.OnfrmtcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_usednm", DbType:="NVarChar(MAX)")>  _
	Public Property usednm() As String
		Get
			Return Me._usednm
		End Get
		Set
			If (String.Equals(Me._usednm, value) = false) Then
				Me.OnusednmChanging(value)
				Me.SendPropertyChanging
				Me._usednm = value
				Me.SendPropertyChanged("usednm")
				Me.OnusednmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_frmtnm", DbType:="NVarChar(MAX)")>  _
	Public Property frmtnm() As String
		Get
			Return Me._frmtnm
		End Get
		Set
			If (String.Equals(Me._frmtnm, value) = false) Then
				Me.OnfrmtnmChanging(value)
				Me.SendPropertyChanging
				Me._frmtnm = value
				Me.SendPropertyChanged("frmtnm")
				Me.OnfrmtnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_chngwtcd", DbType:="NVarChar(MAX)")>  _
	Public Property chngwtcd() As String
		Get
			Return Me._chngwtcd
		End Get
		Set
			If (String.Equals(Me._chngwtcd, value) = false) Then
				Me.OnchngwtcdChanging(value)
				Me.SendPropertyChanging
				Me._chngwtcd = value
				Me.SendPropertyChanged("chngwtcd")
				Me.OnchngwtcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thachngwtnm", DbType:="NVarChar(MAX)")>  _
	Public Property thachngwtnm() As String
		Get
			Return Me._thachngwtnm
		End Get
		Set
			If (String.Equals(Me._thachngwtnm, value) = false) Then
				Me.OnthachngwtnmChanging(value)
				Me.SendPropertyChanging
				Me._thachngwtnm = value
				Me.SendPropertyChanged("thachngwtnm")
				Me.OnthachngwtnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rcvdate_TH", DbType:="NVarChar(MAX)")>  _
	Public Property rcvdate_TH() As String
		Get
			Return Me._rcvdate_TH
		End Get
		Set
			If (String.Equals(Me._rcvdate_TH, value) = false) Then
				Me.Onrcvdate_THChanging(value)
				Me.SendPropertyChanging
				Me._rcvdate_TH = value
				Me.SendPropertyChanged("rcvdate_TH")
				Me.Onrcvdate_THChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rgdate", DbType:="NVarChar(MAX)")>  _
	Public Property rgdate() As String
		Get
			Return Me._rgdate
		End Get
		Set
			If (String.Equals(Me._rgdate, value) = false) Then
				Me.OnrgdateChanging(value)
				Me.SendPropertyChanging
				Me._rgdate = value
				Me.SendPropertyChanged("rgdate")
				Me.OnrgdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rgdate_TH", DbType:="NVarChar(MAX)")>  _
	Public Property rgdate_TH() As String
		Get
			Return Me._rgdate_TH
		End Get
		Set
			If (String.Equals(Me._rgdate_TH, value) = false) Then
				Me.Onrgdate_THChanging(value)
				Me.SendPropertyChanging
				Me._rgdate_TH = value
				Me.SendPropertyChanged("rgdate_TH")
				Me.Onrgdate_THChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_expdate_TH", DbType:="NVarChar(MAX)")>  _
	Public Property expdate_TH() As String
		Get
			Return Me._expdate_TH
		End Get
		Set
			If (String.Equals(Me._expdate_TH, value) = false) Then
				Me.Onexpdate_THChanging(value)
				Me.SendPropertyChanging
				Me._expdate_TH = value
				Me.SendPropertyChanged("expdate_TH")
				Me.Onexpdate_THChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_isocode", DbType:="NVarChar(MAX)")>  _
	Public Property isocode() As String
		Get
			Return Me._isocode
		End Get
		Set
			If (String.Equals(Me._isocode, value) = false) Then
				Me.OnisocodeChanging(value)
				Me.SendPropertyChanging
				Me._isocode = value
				Me.SendPropertyChanged("isocode")
				Me.OnisocodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_engcntnm", DbType:="NVarChar(MAX)")>  _
	Public Property engcntnm() As String
		Get
			Return Me._engcntnm
		End Get
		Set
			If (String.Equals(Me._engcntnm, value) = false) Then
				Me.OnengcntnmChanging(value)
				Me.SendPropertyChanging
				Me._engcntnm = value
				Me.SendPropertyChanged("engcntnm")
				Me.OnengcntnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thacntnm", DbType:="NVarChar(MAX)")>  _
	Public Property thacntnm() As String
		Get
			Return Me._thacntnm
		End Get
		Set
			If (String.Equals(Me._thacntnm, value) = false) Then
				Me.OnthacntnmChanging(value)
				Me.SendPropertyChanging
				Me._thacntnm = value
				Me.SendPropertyChanged("thacntnm")
				Me.OnthacntnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Newcode_R", DbType:="NVarChar(MAX)")>  _
	Public Property Newcode_R() As String
		Get
			Return Me._Newcode_R
		End Get
		Set
			If (String.Equals(Me._Newcode_R, value) = false) Then
				Me.OnNewcode_RChanging(value)
				Me.SendPropertyChanging
				Me._Newcode_R = value
				Me.SendPropertyChanged("Newcode_R")
				Me.OnNewcode_RChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lmdfdate", DbType:="NVarChar(MAX)")>  _
	Public Property lmdfdate() As String
		Get
			Return Me._lmdfdate
		End Get
		Set
			If (String.Equals(Me._lmdfdate, value) = false) Then
				Me.OnlmdfdateChanging(value)
				Me.SendPropertyChanging
				Me._lmdfdate = value
				Me.SendPropertyChanged("lmdfdate")
				Me.OnlmdfdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_qty", DbType:="NVarChar(MAX)")>  _
	Public Property qty() As String
		Get
			Return Me._qty
		End Get
		Set
			If (String.Equals(Me._qty, value) = false) Then
				Me.OnqtyChanging(value)
				Me.SendPropertyChanging
				Me._qty = value
				Me.SendPropertyChanged("qty")
				Me.OnqtyChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_unitnm", DbType:="NVarChar(MAX)")>  _
	Public Property unitnm() As String
		Get
			Return Me._unitnm
		End Get
		Set
			If (String.Equals(Me._unitnm, value) = false) Then
				Me.OnunitnmChanging(value)
				Me.SendPropertyChanging
				Me._unitnm = value
				Me.SendPropertyChanged("unitnm")
				Me.OnunitnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctnm_keep", DbType:="NVarChar(MAX)")>  _
	Public Property lctnm_keep() As String
		Get
			Return Me._lctnm_keep
		End Get
		Set
			If (String.Equals(Me._lctnm_keep, value) = false) Then
				Me.Onlctnm_keepChanging(value)
				Me.SendPropertyChanging
				Me._lctnm_keep = value
				Me.SendPropertyChanged("lctnm_keep")
				Me.Onlctnm_keepChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_address_keep", DbType:="NVarChar(MAX)")>  _
	Public Property address_keep() As String
		Get
			Return Me._address_keep
		End Get
		Set
			If (String.Equals(Me._address_keep, value) = false) Then
				Me.Onaddress_keepChanging(value)
				Me.SendPropertyChanging
				Me._address_keep = value
				Me.SendPropertyChanged("address_keep")
				Me.Onaddress_keepChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_chngwtcd_ask_where", DbType:="NVarChar(MAX)")>  _
	Public Property chngwtcd_ask_where() As String
		Get
			Return Me._chngwtcd_ask_where
		End Get
		Set
			If (String.Equals(Me._chngwtcd_ask_where, value) = false) Then
				Me.Onchngwtcd_ask_whereChanging(value)
				Me.SendPropertyChanging
				Me._chngwtcd_ask_where = value
				Me.SendPropertyChanged("chngwtcd_ask_where")
				Me.Onchngwtcd_ask_whereChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ask_where", DbType:="NVarChar(MAX)")>  _
	Public Property ask_where() As String
		Get
			Return Me._ask_where
		End Get
		Set
			If (String.Equals(Me._ask_where, value) = false) Then
				Me.Onask_whereChanging(value)
				Me.SendPropertyChanging
				Me._ask_where = value
				Me.SendPropertyChanged("ask_where")
				Me.Onask_whereChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_register_lcnno", DbType:="NVarChar(MAX)")>  _
	Public Property register_lcnno() As String
		Get
			Return Me._register_lcnno
		End Get
		Set
			If (String.Equals(Me._register_lcnno, value) = false) Then
				Me.Onregister_lcnnoChanging(value)
				Me.SendPropertyChanging
				Me._register_lcnno = value
				Me.SendPropertyChanged("register_lcnno")
				Me.Onregister_lcnnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cnsdcd", DbType:="NVarChar(MAX)")>  _
	Public Property cnsdcd() As String
		Get
			Return Me._cnsdcd
		End Get
		Set
			If (String.Equals(Me._cnsdcd, value) = false) Then
				Me.OncnsdcdChanging(value)
				Me.SendPropertyChanging
				Me._cnsdcd = value
				Me.SendPropertyChanged("cnsdcd")
				Me.OncnsdcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcntpnm", DbType:="NVarChar(MAX)")>  _
	Public Property lcntpnm() As String
		Get
			Return Me._lcntpnm
		End Get
		Set
			If (String.Equals(Me._lcntpnm, value) = false) Then
				Me.OnlcntpnmChanging(value)
				Me.SendPropertyChanging
				Me._lcntpnm = value
				Me.SendPropertyChanged("lcntpnm")
				Me.OnlcntpnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thanm_manufacture", DbType:="NVarChar(MAX)")>  _
	Public Property thanm_manufacture() As String
		Get
			Return Me._thanm_manufacture
		End Get
		Set
			If (String.Equals(Me._thanm_manufacture, value) = false) Then
				Me.Onthanm_manufactureChanging(value)
				Me.SendPropertyChanging
				Me._thanm_manufacture = value
				Me.SendPropertyChanged("thanm_manufacture")
				Me.Onthanm_manufactureChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thanm_addr_manufacture", DbType:="NVarChar(MAX)")>  _
	Public Property thanm_addr_manufacture() As String
		Get
			Return Me._thanm_addr_manufacture
		End Get
		Set
			If (String.Equals(Me._thanm_addr_manufacture, value) = false) Then
				Me.Onthanm_addr_manufactureChanging(value)
				Me.SendPropertyChanging
				Me._thanm_addr_manufacture = value
				Me.SendPropertyChanged("thanm_addr_manufacture")
				Me.Onthanm_addr_manufactureChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_action_notice", DbType:="NVarChar(MAX)")>  _
	Public Property action_notice() As String
		Get
			Return Me._action_notice
		End Get
		Set
			If (String.Equals(Me._action_notice, value) = false) Then
				Me.Onaction_noticeChanging(value)
				Me.SendPropertyChanging
				Me._action_notice = value
				Me.SendPropertyChanged("action_notice")
				Me.Onaction_noticeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_stunit", DbType:="NVarChar(MAX)")>  _
	Public Property stunit() As String
		Get
			Return Me._stunit
		End Get
		Set
			If (String.Equals(Me._stunit, value) = false) Then
				Me.OnstunitChanging(value)
				Me.SendPropertyChanging
				Me._stunit = value
				Me.SendPropertyChanged("stunit")
				Me.OnstunitChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Newcode_contro", DbType:="NVarChar(MAX)")>  _
	Public Property Newcode_contro() As String
		Get
			Return Me._Newcode_contro
		End Get
		Set
			If (String.Equals(Me._Newcode_contro, value) = false) Then
				Me.OnNewcode_controChanging(value)
				Me.SendPropertyChanging
				Me._Newcode_contro = value
				Me.SendPropertyChanged("Newcode_contro")
				Me.OnNewcode_controChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rcvdate_EN", DbType:="NVarChar(MAX)")>  _
	Public Property rcvdate_EN() As String
		Get
			Return Me._rcvdate_EN
		End Get
		Set
			If (String.Equals(Me._rcvdate_EN, value) = false) Then
				Me.Onrcvdate_ENChanging(value)
				Me.SendPropertyChanging
				Me._rcvdate_EN = value
				Me.SendPropertyChanged("rcvdate_EN")
				Me.Onrcvdate_ENChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_export_nm", DbType:="NVarChar(MAX)")>  _
	Public Property export_nm() As String
		Get
			Return Me._export_nm
		End Get
		Set
			If (String.Equals(Me._export_nm, value) = false) Then
				Me.Onexport_nmChanging(value)
				Me.SendPropertyChanging
				Me._export_nm = value
				Me.SendPropertyChanged("export_nm")
				Me.Onexport_nmChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
