'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="FDA_XML_MDC")>  _
Partial Public Class LGT_FDA_XML_MDCDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertXML_MDC2(instance As XML_MDC2)
    End Sub
  Partial Private Sub UpdateXML_MDC2(instance As XML_MDC2)
    End Sub
  Partial Private Sub DeleteXML_MDC2(instance As XML_MDC2)
    End Sub
  Partial Private Sub InsertLICENSE_HISTORY(instance As LICENSE_HISTORY)
    End Sub
  Partial Private Sub UpdateLICENSE_HISTORY(instance As LICENSE_HISTORY)
    End Sub
  Partial Private Sub DeleteLICENSE_HISTORY(instance As LICENSE_HISTORY)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("FDA_XML_MDCConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property XML_MDC2s() As System.Data.Linq.Table(Of XML_MDC2)
		Get
			Return Me.GetTable(Of XML_MDC2)
		End Get
	End Property
	
	Public ReadOnly Property LICENSE_HISTORies() As System.Data.Linq.Table(Of LICENSE_HISTORY)
		Get
			Return Me.GetTable(Of LICENSE_HISTORY)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.XML_MDC2")>  _
Partial Public Class XML_MDC2
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _pvncd As System.Nullable(Of Integer)
	
	Private _lcnno As System.Nullable(Of Long)
	
	Private _Doc_no As String
	
	Private _lcnsid As System.Nullable(Of Long)
	
	Private _lcntypecd As System.Nullable(Of Integer)
	
	Private _thamdnm As String
	
	Private _engmdnm As String
	
	Private _productnm As String
	
	Private _engfrgnnm As String
	
	Private _cntcd As String
	
	Private _itemno As System.Nullable(Of Integer)
	
	Private _appvdate As System.Nullable(Of Date)
	
	Private _expdate As System.Nullable(Of Date)
	
	Private _appno As String
	
	Private _GroupName As String
	
	Private _Ranking As String
	
	Private _Newcode As String
	
	Private _CAT_NO As String
	
	Private _des As String
	
	Private _own_cntcd As String
	
	Private _IDA As Integer
	
	Private _lctcd As System.Nullable(Of Integer)
	
	Private _lctnmcd As System.Nullable(Of Integer)
	
	Private _lct_name As String
	
	Private _ownername As String
	
	Private _Full_Addr As String
	
	Private _CITIZEN_ID As String
	
	Private _LCN_DISPLAY As String
	
	Private _LCN_SEARCH As String
	
	Private _frgn_addr As String
	
	Private _EXP_DATE_TEMP As String
	
	Private _STATUS_ID As String
	
	Private _ABBR As String
	
	Private _STATUS_NAME As String
	
	Private _PAY_DATE As System.Nullable(Of Date)
	
	Private _engcntnm As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnpvncdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnpvncdChanged()
    End Sub
    Partial Private Sub OnlcnnoChanging(value As System.Nullable(Of Long))
    End Sub
    Partial Private Sub OnlcnnoChanged()
    End Sub
    Partial Private Sub OnDoc_noChanging(value As String)
    End Sub
    Partial Private Sub OnDoc_noChanged()
    End Sub
    Partial Private Sub OnlcnsidChanging(value As System.Nullable(Of Long))
    End Sub
    Partial Private Sub OnlcnsidChanged()
    End Sub
    Partial Private Sub OnlcntypecdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcntypecdChanged()
    End Sub
    Partial Private Sub OnthamdnmChanging(value As String)
    End Sub
    Partial Private Sub OnthamdnmChanged()
    End Sub
    Partial Private Sub OnengmdnmChanging(value As String)
    End Sub
    Partial Private Sub OnengmdnmChanged()
    End Sub
    Partial Private Sub OnproductnmChanging(value As String)
    End Sub
    Partial Private Sub OnproductnmChanged()
    End Sub
    Partial Private Sub OnengfrgnnmChanging(value As String)
    End Sub
    Partial Private Sub OnengfrgnnmChanged()
    End Sub
    Partial Private Sub OncntcdChanging(value As String)
    End Sub
    Partial Private Sub OncntcdChanged()
    End Sub
    Partial Private Sub OnitemnoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnitemnoChanged()
    End Sub
    Partial Private Sub OnappvdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnappvdateChanged()
    End Sub
    Partial Private Sub OnexpdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnexpdateChanged()
    End Sub
    Partial Private Sub OnappnoChanging(value As String)
    End Sub
    Partial Private Sub OnappnoChanged()
    End Sub
    Partial Private Sub OnGroupNameChanging(value As String)
    End Sub
    Partial Private Sub OnGroupNameChanged()
    End Sub
    Partial Private Sub OnRankingChanging(value As String)
    End Sub
    Partial Private Sub OnRankingChanged()
    End Sub
    Partial Private Sub OnNewcodeChanging(value As String)
    End Sub
    Partial Private Sub OnNewcodeChanged()
    End Sub
    Partial Private Sub OnCAT_NOChanging(value As String)
    End Sub
    Partial Private Sub OnCAT_NOChanged()
    End Sub
    Partial Private Sub OndesChanging(value As String)
    End Sub
    Partial Private Sub OndesChanged()
    End Sub
    Partial Private Sub Onown_cntcdChanging(value As String)
    End Sub
    Partial Private Sub Onown_cntcdChanged()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnlctcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlctcdChanged()
    End Sub
    Partial Private Sub OnlctnmcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlctnmcdChanged()
    End Sub
    Partial Private Sub Onlct_nameChanging(value As String)
    End Sub
    Partial Private Sub Onlct_nameChanged()
    End Sub
    Partial Private Sub OnownernameChanging(value As String)
    End Sub
    Partial Private Sub OnownernameChanged()
    End Sub
    Partial Private Sub OnFull_AddrChanging(value As String)
    End Sub
    Partial Private Sub OnFull_AddrChanged()
    End Sub
    Partial Private Sub OnCITIZEN_IDChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_IDChanged()
    End Sub
    Partial Private Sub OnLCN_DISPLAYChanging(value As String)
    End Sub
    Partial Private Sub OnLCN_DISPLAYChanged()
    End Sub
    Partial Private Sub OnLCN_SEARCHChanging(value As String)
    End Sub
    Partial Private Sub OnLCN_SEARCHChanged()
    End Sub
    Partial Private Sub Onfrgn_addrChanging(value As String)
    End Sub
    Partial Private Sub Onfrgn_addrChanged()
    End Sub
    Partial Private Sub OnEXP_DATE_TEMPChanging(value As String)
    End Sub
    Partial Private Sub OnEXP_DATE_TEMPChanged()
    End Sub
    Partial Private Sub OnSTATUS_IDChanging(value As String)
    End Sub
    Partial Private Sub OnSTATUS_IDChanged()
    End Sub
    Partial Private Sub OnABBRChanging(value As String)
    End Sub
    Partial Private Sub OnABBRChanged()
    End Sub
    Partial Private Sub OnSTATUS_NAMEChanging(value As String)
    End Sub
    Partial Private Sub OnSTATUS_NAMEChanged()
    End Sub
    Partial Private Sub OnPAY_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnPAY_DATEChanged()
    End Sub
    Partial Private Sub OnengcntnmChanging(value As String)
    End Sub
    Partial Private Sub OnengcntnmChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pvncd", DbType:="Int")>  _
	Public Property pvncd() As System.Nullable(Of Integer)
		Get
			Return Me._pvncd
		End Get
		Set
			If (Me._pvncd.Equals(value) = false) Then
				Me.OnpvncdChanging(value)
				Me.SendPropertyChanging
				Me._pvncd = value
				Me.SendPropertyChanged("pvncd")
				Me.OnpvncdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnno", DbType:="BigInt")>  _
	Public Property lcnno() As System.Nullable(Of Long)
		Get
			Return Me._lcnno
		End Get
		Set
			If (Me._lcnno.Equals(value) = false) Then
				Me.OnlcnnoChanging(value)
				Me.SendPropertyChanging
				Me._lcnno = value
				Me.SendPropertyChanged("lcnno")
				Me.OnlcnnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Doc_no", DbType:="NVarChar(MAX)")>  _
	Public Property Doc_no() As String
		Get
			Return Me._Doc_no
		End Get
		Set
			If (String.Equals(Me._Doc_no, value) = false) Then
				Me.OnDoc_noChanging(value)
				Me.SendPropertyChanging
				Me._Doc_no = value
				Me.SendPropertyChanged("Doc_no")
				Me.OnDoc_noChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnsid", DbType:="BigInt")>  _
	Public Property lcnsid() As System.Nullable(Of Long)
		Get
			Return Me._lcnsid
		End Get
		Set
			If (Me._lcnsid.Equals(value) = false) Then
				Me.OnlcnsidChanging(value)
				Me.SendPropertyChanging
				Me._lcnsid = value
				Me.SendPropertyChanged("lcnsid")
				Me.OnlcnsidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcntypecd", DbType:="Int")>  _
	Public Property lcntypecd() As System.Nullable(Of Integer)
		Get
			Return Me._lcntypecd
		End Get
		Set
			If (Me._lcntypecd.Equals(value) = false) Then
				Me.OnlcntypecdChanging(value)
				Me.SendPropertyChanging
				Me._lcntypecd = value
				Me.SendPropertyChanged("lcntypecd")
				Me.OnlcntypecdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thamdnm", DbType:="NVarChar(MAX)")>  _
	Public Property thamdnm() As String
		Get
			Return Me._thamdnm
		End Get
		Set
			If (String.Equals(Me._thamdnm, value) = false) Then
				Me.OnthamdnmChanging(value)
				Me.SendPropertyChanging
				Me._thamdnm = value
				Me.SendPropertyChanged("thamdnm")
				Me.OnthamdnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_engmdnm", DbType:="NVarChar(MAX)")>  _
	Public Property engmdnm() As String
		Get
			Return Me._engmdnm
		End Get
		Set
			If (String.Equals(Me._engmdnm, value) = false) Then
				Me.OnengmdnmChanging(value)
				Me.SendPropertyChanging
				Me._engmdnm = value
				Me.SendPropertyChanged("engmdnm")
				Me.OnengmdnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_productnm", DbType:="NVarChar(MAX)")>  _
	Public Property productnm() As String
		Get
			Return Me._productnm
		End Get
		Set
			If (String.Equals(Me._productnm, value) = false) Then
				Me.OnproductnmChanging(value)
				Me.SendPropertyChanging
				Me._productnm = value
				Me.SendPropertyChanged("productnm")
				Me.OnproductnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_engfrgnnm", DbType:="NVarChar(MAX)")>  _
	Public Property engfrgnnm() As String
		Get
			Return Me._engfrgnnm
		End Get
		Set
			If (String.Equals(Me._engfrgnnm, value) = false) Then
				Me.OnengfrgnnmChanging(value)
				Me.SendPropertyChanging
				Me._engfrgnnm = value
				Me.SendPropertyChanged("engfrgnnm")
				Me.OnengfrgnnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cntcd", DbType:="Char(3)")>  _
	Public Property cntcd() As String
		Get
			Return Me._cntcd
		End Get
		Set
			If (String.Equals(Me._cntcd, value) = false) Then
				Me.OncntcdChanging(value)
				Me.SendPropertyChanging
				Me._cntcd = value
				Me.SendPropertyChanged("cntcd")
				Me.OncntcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_itemno", DbType:="Int")>  _
	Public Property itemno() As System.Nullable(Of Integer)
		Get
			Return Me._itemno
		End Get
		Set
			If (Me._itemno.Equals(value) = false) Then
				Me.OnitemnoChanging(value)
				Me.SendPropertyChanging
				Me._itemno = value
				Me.SendPropertyChanged("itemno")
				Me.OnitemnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_appvdate", DbType:="Date")>  _
	Public Property appvdate() As System.Nullable(Of Date)
		Get
			Return Me._appvdate
		End Get
		Set
			If (Me._appvdate.Equals(value) = false) Then
				Me.OnappvdateChanging(value)
				Me.SendPropertyChanging
				Me._appvdate = value
				Me.SendPropertyChanged("appvdate")
				Me.OnappvdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_expdate", DbType:="Date")>  _
	Public Property expdate() As System.Nullable(Of Date)
		Get
			Return Me._expdate
		End Get
		Set
			If (Me._expdate.Equals(value) = false) Then
				Me.OnexpdateChanging(value)
				Me.SendPropertyChanging
				Me._expdate = value
				Me.SendPropertyChanged("expdate")
				Me.OnexpdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_appno", DbType:="NVarChar(MAX)")>  _
	Public Property appno() As String
		Get
			Return Me._appno
		End Get
		Set
			If (String.Equals(Me._appno, value) = false) Then
				Me.OnappnoChanging(value)
				Me.SendPropertyChanging
				Me._appno = value
				Me.SendPropertyChanged("appno")
				Me.OnappnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GroupName", DbType:="VarChar(10)")>  _
	Public Property GroupName() As String
		Get
			Return Me._GroupName
		End Get
		Set
			If (String.Equals(Me._GroupName, value) = false) Then
				Me.OnGroupNameChanging(value)
				Me.SendPropertyChanging
				Me._GroupName = value
				Me.SendPropertyChanged("GroupName")
				Me.OnGroupNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Ranking", DbType:="VarChar(1)")>  _
	Public Property Ranking() As String
		Get
			Return Me._Ranking
		End Get
		Set
			If (String.Equals(Me._Ranking, value) = false) Then
				Me.OnRankingChanging(value)
				Me.SendPropertyChanging
				Me._Ranking = value
				Me.SendPropertyChanged("Ranking")
				Me.OnRankingChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Newcode", DbType:="NVarChar(MAX)")>  _
	Public Property Newcode() As String
		Get
			Return Me._Newcode
		End Get
		Set
			If (String.Equals(Me._Newcode, value) = false) Then
				Me.OnNewcodeChanging(value)
				Me.SendPropertyChanging
				Me._Newcode = value
				Me.SendPropertyChanged("Newcode")
				Me.OnNewcodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CAT_NO", DbType:="NVarChar(MAX)")>  _
	Public Property CAT_NO() As String
		Get
			Return Me._CAT_NO
		End Get
		Set
			If (String.Equals(Me._CAT_NO, value) = false) Then
				Me.OnCAT_NOChanging(value)
				Me.SendPropertyChanging
				Me._CAT_NO = value
				Me.SendPropertyChanged("CAT_NO")
				Me.OnCAT_NOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_des", DbType:="NVarChar(MAX)")>  _
	Public Property des() As String
		Get
			Return Me._des
		End Get
		Set
			If (String.Equals(Me._des, value) = false) Then
				Me.OndesChanging(value)
				Me.SendPropertyChanging
				Me._des = value
				Me.SendPropertyChanged("des")
				Me.OndesChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_own_cntcd", DbType:="NVarChar(50)")>  _
	Public Property own_cntcd() As String
		Get
			Return Me._own_cntcd
		End Get
		Set
			If (String.Equals(Me._own_cntcd, value) = false) Then
				Me.Onown_cntcdChanging(value)
				Me.SendPropertyChanging
				Me._own_cntcd = value
				Me.SendPropertyChanged("own_cntcd")
				Me.Onown_cntcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctcd", DbType:="Int")>  _
	Public Property lctcd() As System.Nullable(Of Integer)
		Get
			Return Me._lctcd
		End Get
		Set
			If (Me._lctcd.Equals(value) = false) Then
				Me.OnlctcdChanging(value)
				Me.SendPropertyChanging
				Me._lctcd = value
				Me.SendPropertyChanged("lctcd")
				Me.OnlctcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctnmcd", DbType:="Int")>  _
	Public Property lctnmcd() As System.Nullable(Of Integer)
		Get
			Return Me._lctnmcd
		End Get
		Set
			If (Me._lctnmcd.Equals(value) = false) Then
				Me.OnlctnmcdChanging(value)
				Me.SendPropertyChanging
				Me._lctnmcd = value
				Me.SendPropertyChanged("lctnmcd")
				Me.OnlctnmcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lct_name", DbType:="VarChar(MAX)")>  _
	Public Property lct_name() As String
		Get
			Return Me._lct_name
		End Get
		Set
			If (String.Equals(Me._lct_name, value) = false) Then
				Me.Onlct_nameChanging(value)
				Me.SendPropertyChanging
				Me._lct_name = value
				Me.SendPropertyChanged("lct_name")
				Me.Onlct_nameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ownername", DbType:="VarChar(MAX)")>  _
	Public Property ownername() As String
		Get
			Return Me._ownername
		End Get
		Set
			If (String.Equals(Me._ownername, value) = false) Then
				Me.OnownernameChanging(value)
				Me.SendPropertyChanging
				Me._ownername = value
				Me.SendPropertyChanged("ownername")
				Me.OnownernameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Full_Addr", DbType:="VarChar(MAX)")>  _
	Public Property Full_Addr() As String
		Get
			Return Me._Full_Addr
		End Get
		Set
			If (String.Equals(Me._Full_Addr, value) = false) Then
				Me.OnFull_AddrChanging(value)
				Me.SendPropertyChanging
				Me._Full_Addr = value
				Me.SendPropertyChanged("Full_Addr")
				Me.OnFull_AddrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_ID", DbType:="VarChar(50)")>  _
	Public Property CITIZEN_ID() As String
		Get
			Return Me._CITIZEN_ID
		End Get
		Set
			If (String.Equals(Me._CITIZEN_ID, value) = false) Then
				Me.OnCITIZEN_IDChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_ID = value
				Me.SendPropertyChanged("CITIZEN_ID")
				Me.OnCITIZEN_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCN_DISPLAY", DbType:="VarChar(50)")>  _
	Public Property LCN_DISPLAY() As String
		Get
			Return Me._LCN_DISPLAY
		End Get
		Set
			If (String.Equals(Me._LCN_DISPLAY, value) = false) Then
				Me.OnLCN_DISPLAYChanging(value)
				Me.SendPropertyChanging
				Me._LCN_DISPLAY = value
				Me.SendPropertyChanged("LCN_DISPLAY")
				Me.OnLCN_DISPLAYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCN_SEARCH", DbType:="VarChar(50)")>  _
	Public Property LCN_SEARCH() As String
		Get
			Return Me._LCN_SEARCH
		End Get
		Set
			If (String.Equals(Me._LCN_SEARCH, value) = false) Then
				Me.OnLCN_SEARCHChanging(value)
				Me.SendPropertyChanging
				Me._LCN_SEARCH = value
				Me.SendPropertyChanged("LCN_SEARCH")
				Me.OnLCN_SEARCHChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_frgn_addr", DbType:="NVarChar(MAX)")>  _
	Public Property frgn_addr() As String
		Get
			Return Me._frgn_addr
		End Get
		Set
			If (String.Equals(Me._frgn_addr, value) = false) Then
				Me.Onfrgn_addrChanging(value)
				Me.SendPropertyChanging
				Me._frgn_addr = value
				Me.SendPropertyChanged("frgn_addr")
				Me.Onfrgn_addrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EXP_DATE_TEMP", DbType:="NVarChar(MAX)")>  _
	Public Property EXP_DATE_TEMP() As String
		Get
			Return Me._EXP_DATE_TEMP
		End Get
		Set
			If (String.Equals(Me._EXP_DATE_TEMP, value) = false) Then
				Me.OnEXP_DATE_TEMPChanging(value)
				Me.SendPropertyChanging
				Me._EXP_DATE_TEMP = value
				Me.SendPropertyChanged("EXP_DATE_TEMP")
				Me.OnEXP_DATE_TEMPChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STATUS_ID", DbType:="NChar(10)")>  _
	Public Property STATUS_ID() As String
		Get
			Return Me._STATUS_ID
		End Get
		Set
			If (String.Equals(Me._STATUS_ID, value) = false) Then
				Me.OnSTATUS_IDChanging(value)
				Me.SendPropertyChanging
				Me._STATUS_ID = value
				Me.SendPropertyChanged("STATUS_ID")
				Me.OnSTATUS_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ABBR", DbType:="NVarChar(50)")>  _
	Public Property ABBR() As String
		Get
			Return Me._ABBR
		End Get
		Set
			If (String.Equals(Me._ABBR, value) = false) Then
				Me.OnABBRChanging(value)
				Me.SendPropertyChanging
				Me._ABBR = value
				Me.SendPropertyChanged("ABBR")
				Me.OnABBRChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STATUS_NAME", DbType:="NVarChar(MAX)")>  _
	Public Property STATUS_NAME() As String
		Get
			Return Me._STATUS_NAME
		End Get
		Set
			If (String.Equals(Me._STATUS_NAME, value) = false) Then
				Me.OnSTATUS_NAMEChanging(value)
				Me.SendPropertyChanging
				Me._STATUS_NAME = value
				Me.SendPropertyChanged("STATUS_NAME")
				Me.OnSTATUS_NAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PAY_DATE", DbType:="DateTime")>  _
	Public Property PAY_DATE() As System.Nullable(Of Date)
		Get
			Return Me._PAY_DATE
		End Get
		Set
			If (Me._PAY_DATE.Equals(value) = false) Then
				Me.OnPAY_DATEChanging(value)
				Me.SendPropertyChanging
				Me._PAY_DATE = value
				Me.SendPropertyChanged("PAY_DATE")
				Me.OnPAY_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_engcntnm", DbType:="NVarChar(MAX)")>  _
	Public Property engcntnm() As String
		Get
			Return Me._engcntnm
		End Get
		Set
			If (String.Equals(Me._engcntnm, value) = false) Then
				Me.OnengcntnmChanging(value)
				Me.SendPropertyChanging
				Me._engcntnm = value
				Me.SendPropertyChanged("engcntnm")
				Me.OnengcntnmChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.LICENSE_HISTORY")>  _
Partial Public Class LICENSE_HISTORY
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDA As Integer
	
	Private _APPVDATE As System.Nullable(Of Date)
	
	Private _LCTNO As String
	
	Private _LCNNO As String
	
	Private _TYPE As String
	
	Private _TOPIC As String
	
	Private _TEXT_OLD As String
	
	Private _TEXT_NEW As String
	
	Private _RCVNO As String
	
	Private _RCVDATE As System.Nullable(Of Date)
	
	Private _DESCRIPTION As String
	
	Private _REF_NO As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnAPPVDATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnAPPVDATEChanged()
    End Sub
    Partial Private Sub OnLCTNOChanging(value As String)
    End Sub
    Partial Private Sub OnLCTNOChanged()
    End Sub
    Partial Private Sub OnLCNNOChanging(value As String)
    End Sub
    Partial Private Sub OnLCNNOChanged()
    End Sub
    Partial Private Sub OnTYPEChanging(value As String)
    End Sub
    Partial Private Sub OnTYPEChanged()
    End Sub
    Partial Private Sub OnTOPICChanging(value As String)
    End Sub
    Partial Private Sub OnTOPICChanged()
    End Sub
    Partial Private Sub OnTEXT_OLDChanging(value As String)
    End Sub
    Partial Private Sub OnTEXT_OLDChanged()
    End Sub
    Partial Private Sub OnTEXT_NEWChanging(value As String)
    End Sub
    Partial Private Sub OnTEXT_NEWChanged()
    End Sub
    Partial Private Sub OnRCVNOChanging(value As String)
    End Sub
    Partial Private Sub OnRCVNOChanged()
    End Sub
    Partial Private Sub OnRCVDATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnRCVDATEChanged()
    End Sub
    Partial Private Sub OnDESCRIPTIONChanging(value As String)
    End Sub
    Partial Private Sub OnDESCRIPTIONChanged()
    End Sub
    Partial Private Sub OnREF_NOChanging(value As String)
    End Sub
    Partial Private Sub OnREF_NOChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_APPVDATE", DbType:="DateTime")>  _
	Public Property APPVDATE() As System.Nullable(Of Date)
		Get
			Return Me._APPVDATE
		End Get
		Set
			If (Me._APPVDATE.Equals(value) = false) Then
				Me.OnAPPVDATEChanging(value)
				Me.SendPropertyChanging
				Me._APPVDATE = value
				Me.SendPropertyChanged("APPVDATE")
				Me.OnAPPVDATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCTNO", DbType:="NVarChar(50)")>  _
	Public Property LCTNO() As String
		Get
			Return Me._LCTNO
		End Get
		Set
			If (String.Equals(Me._LCTNO, value) = false) Then
				Me.OnLCTNOChanging(value)
				Me.SendPropertyChanging
				Me._LCTNO = value
				Me.SendPropertyChanged("LCTNO")
				Me.OnLCTNOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCNNO", DbType:="NVarChar(50)")>  _
	Public Property LCNNO() As String
		Get
			Return Me._LCNNO
		End Get
		Set
			If (String.Equals(Me._LCNNO, value) = false) Then
				Me.OnLCNNOChanging(value)
				Me.SendPropertyChanging
				Me._LCNNO = value
				Me.SendPropertyChanged("LCNNO")
				Me.OnLCNNOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TYPE", DbType:="NVarChar(100)")>  _
	Public Property TYPE() As String
		Get
			Return Me._TYPE
		End Get
		Set
			If (String.Equals(Me._TYPE, value) = false) Then
				Me.OnTYPEChanging(value)
				Me.SendPropertyChanging
				Me._TYPE = value
				Me.SendPropertyChanged("TYPE")
				Me.OnTYPEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TOPIC", DbType:="NVarChar(MAX)")>  _
	Public Property TOPIC() As String
		Get
			Return Me._TOPIC
		End Get
		Set
			If (String.Equals(Me._TOPIC, value) = false) Then
				Me.OnTOPICChanging(value)
				Me.SendPropertyChanging
				Me._TOPIC = value
				Me.SendPropertyChanged("TOPIC")
				Me.OnTOPICChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TEXT_OLD", DbType:="NVarChar(MAX)")>  _
	Public Property TEXT_OLD() As String
		Get
			Return Me._TEXT_OLD
		End Get
		Set
			If (String.Equals(Me._TEXT_OLD, value) = false) Then
				Me.OnTEXT_OLDChanging(value)
				Me.SendPropertyChanging
				Me._TEXT_OLD = value
				Me.SendPropertyChanged("TEXT_OLD")
				Me.OnTEXT_OLDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TEXT_NEW", DbType:="NVarChar(MAX)")>  _
	Public Property TEXT_NEW() As String
		Get
			Return Me._TEXT_NEW
		End Get
		Set
			If (String.Equals(Me._TEXT_NEW, value) = false) Then
				Me.OnTEXT_NEWChanging(value)
				Me.SendPropertyChanging
				Me._TEXT_NEW = value
				Me.SendPropertyChanged("TEXT_NEW")
				Me.OnTEXT_NEWChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RCVNO", DbType:="NVarChar(50)")>  _
	Public Property RCVNO() As String
		Get
			Return Me._RCVNO
		End Get
		Set
			If (String.Equals(Me._RCVNO, value) = false) Then
				Me.OnRCVNOChanging(value)
				Me.SendPropertyChanging
				Me._RCVNO = value
				Me.SendPropertyChanged("RCVNO")
				Me.OnRCVNOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RCVDATE", DbType:="DateTime")>  _
	Public Property RCVDATE() As System.Nullable(Of Date)
		Get
			Return Me._RCVDATE
		End Get
		Set
			If (Me._RCVDATE.Equals(value) = false) Then
				Me.OnRCVDATEChanging(value)
				Me.SendPropertyChanging
				Me._RCVDATE = value
				Me.SendPropertyChanged("RCVDATE")
				Me.OnRCVDATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DESCRIPTION", DbType:="NVarChar(MAX)")>  _
	Public Property DESCRIPTION() As String
		Get
			Return Me._DESCRIPTION
		End Get
		Set
			If (String.Equals(Me._DESCRIPTION, value) = false) Then
				Me.OnDESCRIPTIONChanging(value)
				Me.SendPropertyChanging
				Me._DESCRIPTION = value
				Me.SendPropertyChanged("DESCRIPTION")
				Me.OnDESCRIPTIONChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REF_NO", DbType:="NVarChar(80)")>  _
	Public Property REF_NO() As String
		Get
			Return Me._REF_NO
		End Get
		Set
			If (String.Equals(Me._REF_NO, value) = false) Then
				Me.OnREF_NOChanging(value)
				Me.SendPropertyChanging
				Me._REF_NO = value
				Me.SendPropertyChanged("REF_NO")
				Me.OnREF_NOChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
