<?xml version="1.0" encoding="utf-8"?><Database Name="FDA_XML_CONFIG" Class="LGT_XML_CONFIGDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=164.115.28.124;Initial Catalog=FDA_XML_CONFIG;User ID=fusion" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FDA_XML_CONFIGConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.XML_CONFIG" Member="XML_CONFIGs">
    <Type Name="XML_CONFIG">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="XML_SQL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XML_TYPE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="XML_PATH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XML_DESCRIPTION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XML_HEADER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XML_BODY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XML_FIELDS_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>