'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="FDA_XML")>  _
Partial Public Class LGT_XMLDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertXML_FOOD(instance As XML_FOOD)
    End Sub
  Partial Private Sub UpdateXML_FOOD(instance As XML_FOOD)
    End Sub
  Partial Private Sub DeleteXML_FOOD(instance As XML_FOOD)
    End Sub
  Partial Private Sub InsertXML_CMT(instance As XML_CMT)
    End Sub
  Partial Private Sub UpdateXML_CMT(instance As XML_CMT)
    End Sub
  Partial Private Sub DeleteXML_CMT(instance As XML_CMT)
    End Sub
  Partial Private Sub InsertXML_TXC(instance As XML_TXC)
    End Sub
  Partial Private Sub UpdateXML_TXC(instance As XML_TXC)
    End Sub
  Partial Private Sub DeleteXML_TXC(instance As XML_TXC)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("FDA_XMLConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property XML_FOODs() As System.Data.Linq.Table(Of XML_FOOD)
		Get
			Return Me.GetTable(Of XML_FOOD)
		End Get
	End Property
	
	Public ReadOnly Property XML_CMTs() As System.Data.Linq.Table(Of XML_CMT)
		Get
			Return Me.GetTable(Of XML_CMT)
		End Get
	End Property
	
	Public ReadOnly Property XML_TXCs() As System.Data.Linq.Table(Of XML_TXC)
		Get
			Return Me.GetTable(Of XML_TXC)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.XML_FOOD")>  _
Partial Public Class XML_FOOD
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDA As Integer
	
	Private _pvncd As System.Nullable(Of Short)
	
	Private _lcnno As System.Nullable(Of Integer)
	
	Private _lcnsid As System.Nullable(Of Integer)
	
	Private _fdpdtno As String
	
	Private _lcntypecd As System.Nullable(Of Integer)
	
	Private _prdnmt As String
	
	Private _prdnme As String
	
	Private _Producer_Name As String
	
	Private _groupname As String
	
	Private _NewCode As String
	
	Private _Ranking As String
	
	Private _cntcd As String
	
	Private _appdate As String
	
	Private _expdate As System.Nullable(Of Date)
	
	Private _CreateDate As System.Nullable(Of Date)
	
	Private _UpdateDate As System.Nullable(Of Date)
	
	Private _rid As System.Nullable(Of Integer)
	
	Private _Cer_expdate As System.Nullable(Of Date)
	
	Private _Brand As String
	
	Private _thanm As String
	
	Private _Status As System.Nullable(Of Integer)
	
	Private _Addr As String
	
	Private _fdtypecd As System.Nullable(Of Integer)
	
	Private _fdtypenm As String
	
	Private _thanmowner As String
	
	Private _EXP As String
	
	Private _lctlcnno As String
	
	Private _CITIZEN_AUTHORIZE As String
	
	Private _SUBPDT As String
	
	Private _MTHCD As String
	
	Private _frgn_addr As String
	
	Private _LCN_STATUS As System.Nullable(Of Integer)
	
	Private _LCN_STATUS_NAME As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnpvncdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnpvncdChanged()
    End Sub
    Partial Private Sub OnlcnnoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcnnoChanged()
    End Sub
    Partial Private Sub OnlcnsidChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcnsidChanged()
    End Sub
    Partial Private Sub OnfdpdtnoChanging(value As String)
    End Sub
    Partial Private Sub OnfdpdtnoChanged()
    End Sub
    Partial Private Sub OnlcntypecdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcntypecdChanged()
    End Sub
    Partial Private Sub OnprdnmtChanging(value As String)
    End Sub
    Partial Private Sub OnprdnmtChanged()
    End Sub
    Partial Private Sub OnprdnmeChanging(value As String)
    End Sub
    Partial Private Sub OnprdnmeChanged()
    End Sub
    Partial Private Sub OnProducer_NameChanging(value As String)
    End Sub
    Partial Private Sub OnProducer_NameChanged()
    End Sub
    Partial Private Sub OngroupnameChanging(value As String)
    End Sub
    Partial Private Sub OngroupnameChanged()
    End Sub
    Partial Private Sub OnNewCodeChanging(value As String)
    End Sub
    Partial Private Sub OnNewCodeChanged()
    End Sub
    Partial Private Sub OnRankingChanging(value As String)
    End Sub
    Partial Private Sub OnRankingChanged()
    End Sub
    Partial Private Sub OncntcdChanging(value As String)
    End Sub
    Partial Private Sub OncntcdChanged()
    End Sub
    Partial Private Sub OnappdateChanging(value As String)
    End Sub
    Partial Private Sub OnappdateChanged()
    End Sub
    Partial Private Sub OnexpdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnexpdateChanged()
    End Sub
    Partial Private Sub OnCreateDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCreateDateChanged()
    End Sub
    Partial Private Sub OnUpdateDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnUpdateDateChanged()
    End Sub
    Partial Private Sub OnridChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnridChanged()
    End Sub
    Partial Private Sub OnCer_expdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCer_expdateChanged()
    End Sub
    Partial Private Sub OnBrandChanging(value As String)
    End Sub
    Partial Private Sub OnBrandChanged()
    End Sub
    Partial Private Sub OnthanmChanging(value As String)
    End Sub
    Partial Private Sub OnthanmChanged()
    End Sub
    Partial Private Sub OnStatusChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnStatusChanged()
    End Sub
    Partial Private Sub OnAddrChanging(value As String)
    End Sub
    Partial Private Sub OnAddrChanged()
    End Sub
    Partial Private Sub OnfdtypecdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnfdtypecdChanged()
    End Sub
    Partial Private Sub OnfdtypenmChanging(value As String)
    End Sub
    Partial Private Sub OnfdtypenmChanged()
    End Sub
    Partial Private Sub OnthanmownerChanging(value As String)
    End Sub
    Partial Private Sub OnthanmownerChanged()
    End Sub
    Partial Private Sub OnEXPChanging(value As String)
    End Sub
    Partial Private Sub OnEXPChanged()
    End Sub
    Partial Private Sub OnlctlcnnoChanging(value As String)
    End Sub
    Partial Private Sub OnlctlcnnoChanged()
    End Sub
    Partial Private Sub OnCITIZEN_AUTHORIZEChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_AUTHORIZEChanged()
    End Sub
    Partial Private Sub OnSUBPDTChanging(value As String)
    End Sub
    Partial Private Sub OnSUBPDTChanged()
    End Sub
    Partial Private Sub OnMTHCDChanging(value As String)
    End Sub
    Partial Private Sub OnMTHCDChanged()
    End Sub
    Partial Private Sub Onfrgn_addrChanging(value As String)
    End Sub
    Partial Private Sub Onfrgn_addrChanged()
    End Sub
    Partial Private Sub OnLCN_STATUSChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnLCN_STATUSChanged()
    End Sub
    Partial Private Sub OnLCN_STATUS_NAMEChanging(value As String)
    End Sub
    Partial Private Sub OnLCN_STATUS_NAMEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pvncd", DbType:="SmallInt")>  _
	Public Property pvncd() As System.Nullable(Of Short)
		Get
			Return Me._pvncd
		End Get
		Set
			If (Me._pvncd.Equals(value) = false) Then
				Me.OnpvncdChanging(value)
				Me.SendPropertyChanging
				Me._pvncd = value
				Me.SendPropertyChanged("pvncd")
				Me.OnpvncdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnno", DbType:="Int")>  _
	Public Property lcnno() As System.Nullable(Of Integer)
		Get
			Return Me._lcnno
		End Get
		Set
			If (Me._lcnno.Equals(value) = false) Then
				Me.OnlcnnoChanging(value)
				Me.SendPropertyChanging
				Me._lcnno = value
				Me.SendPropertyChanged("lcnno")
				Me.OnlcnnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnsid", DbType:="Int")>  _
	Public Property lcnsid() As System.Nullable(Of Integer)
		Get
			Return Me._lcnsid
		End Get
		Set
			If (Me._lcnsid.Equals(value) = false) Then
				Me.OnlcnsidChanging(value)
				Me.SendPropertyChanging
				Me._lcnsid = value
				Me.SendPropertyChanged("lcnsid")
				Me.OnlcnsidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fdpdtno", DbType:="NVarChar(255)")>  _
	Public Property fdpdtno() As String
		Get
			Return Me._fdpdtno
		End Get
		Set
			If (String.Equals(Me._fdpdtno, value) = false) Then
				Me.OnfdpdtnoChanging(value)
				Me.SendPropertyChanging
				Me._fdpdtno = value
				Me.SendPropertyChanged("fdpdtno")
				Me.OnfdpdtnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcntypecd", DbType:="Int")>  _
	Public Property lcntypecd() As System.Nullable(Of Integer)
		Get
			Return Me._lcntypecd
		End Get
		Set
			If (Me._lcntypecd.Equals(value) = false) Then
				Me.OnlcntypecdChanging(value)
				Me.SendPropertyChanging
				Me._lcntypecd = value
				Me.SendPropertyChanged("lcntypecd")
				Me.OnlcntypecdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_prdnmt", DbType:="NVarChar(MAX)")>  _
	Public Property prdnmt() As String
		Get
			Return Me._prdnmt
		End Get
		Set
			If (String.Equals(Me._prdnmt, value) = false) Then
				Me.OnprdnmtChanging(value)
				Me.SendPropertyChanging
				Me._prdnmt = value
				Me.SendPropertyChanged("prdnmt")
				Me.OnprdnmtChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_prdnme", DbType:="NVarChar(MAX)")>  _
	Public Property prdnme() As String
		Get
			Return Me._prdnme
		End Get
		Set
			If (String.Equals(Me._prdnme, value) = false) Then
				Me.OnprdnmeChanging(value)
				Me.SendPropertyChanging
				Me._prdnme = value
				Me.SendPropertyChanged("prdnme")
				Me.OnprdnmeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Producer_Name", DbType:="NVarChar(MAX)")>  _
	Public Property Producer_Name() As String
		Get
			Return Me._Producer_Name
		End Get
		Set
			If (String.Equals(Me._Producer_Name, value) = false) Then
				Me.OnProducer_NameChanging(value)
				Me.SendPropertyChanging
				Me._Producer_Name = value
				Me.SendPropertyChanged("Producer_Name")
				Me.OnProducer_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_groupname", DbType:="NVarChar(50)")>  _
	Public Property groupname() As String
		Get
			Return Me._groupname
		End Get
		Set
			If (String.Equals(Me._groupname, value) = false) Then
				Me.OngroupnameChanging(value)
				Me.SendPropertyChanging
				Me._groupname = value
				Me.SendPropertyChanged("groupname")
				Me.OngroupnameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NewCode", DbType:="NVarChar(MAX)")>  _
	Public Property NewCode() As String
		Get
			Return Me._NewCode
		End Get
		Set
			If (String.Equals(Me._NewCode, value) = false) Then
				Me.OnNewCodeChanging(value)
				Me.SendPropertyChanging
				Me._NewCode = value
				Me.SendPropertyChanged("NewCode")
				Me.OnNewCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Ranking", DbType:="NVarChar(50)")>  _
	Public Property Ranking() As String
		Get
			Return Me._Ranking
		End Get
		Set
			If (String.Equals(Me._Ranking, value) = false) Then
				Me.OnRankingChanging(value)
				Me.SendPropertyChanging
				Me._Ranking = value
				Me.SendPropertyChanged("Ranking")
				Me.OnRankingChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cntcd", DbType:="NVarChar(50)")>  _
	Public Property cntcd() As String
		Get
			Return Me._cntcd
		End Get
		Set
			If (String.Equals(Me._cntcd, value) = false) Then
				Me.OncntcdChanging(value)
				Me.SendPropertyChanging
				Me._cntcd = value
				Me.SendPropertyChanged("cntcd")
				Me.OncntcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_appdate", DbType:="NVarChar(MAX)")>  _
	Public Property appdate() As String
		Get
			Return Me._appdate
		End Get
		Set
			If (String.Equals(Me._appdate, value) = false) Then
				Me.OnappdateChanging(value)
				Me.SendPropertyChanging
				Me._appdate = value
				Me.SendPropertyChanged("appdate")
				Me.OnappdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_expdate", DbType:="DateTime")>  _
	Public Property expdate() As System.Nullable(Of Date)
		Get
			Return Me._expdate
		End Get
		Set
			If (Me._expdate.Equals(value) = false) Then
				Me.OnexpdateChanging(value)
				Me.SendPropertyChanging
				Me._expdate = value
				Me.SendPropertyChanged("expdate")
				Me.OnexpdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreateDate", DbType:="DateTime")>  _
	Public Property CreateDate() As System.Nullable(Of Date)
		Get
			Return Me._CreateDate
		End Get
		Set
			If (Me._CreateDate.Equals(value) = false) Then
				Me.OnCreateDateChanging(value)
				Me.SendPropertyChanging
				Me._CreateDate = value
				Me.SendPropertyChanged("CreateDate")
				Me.OnCreateDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UpdateDate", DbType:="DateTime")>  _
	Public Property UpdateDate() As System.Nullable(Of Date)
		Get
			Return Me._UpdateDate
		End Get
		Set
			If (Me._UpdateDate.Equals(value) = false) Then
				Me.OnUpdateDateChanging(value)
				Me.SendPropertyChanging
				Me._UpdateDate = value
				Me.SendPropertyChanged("UpdateDate")
				Me.OnUpdateDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rid", DbType:="Int")>  _
	Public Property rid() As System.Nullable(Of Integer)
		Get
			Return Me._rid
		End Get
		Set
			If (Me._rid.Equals(value) = false) Then
				Me.OnridChanging(value)
				Me.SendPropertyChanging
				Me._rid = value
				Me.SendPropertyChanged("rid")
				Me.OnridChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Cer_expdate", DbType:="DateTime")>  _
	Public Property Cer_expdate() As System.Nullable(Of Date)
		Get
			Return Me._Cer_expdate
		End Get
		Set
			If (Me._Cer_expdate.Equals(value) = false) Then
				Me.OnCer_expdateChanging(value)
				Me.SendPropertyChanging
				Me._Cer_expdate = value
				Me.SendPropertyChanged("Cer_expdate")
				Me.OnCer_expdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Brand", DbType:="NVarChar(MAX)")>  _
	Public Property Brand() As String
		Get
			Return Me._Brand
		End Get
		Set
			If (String.Equals(Me._Brand, value) = false) Then
				Me.OnBrandChanging(value)
				Me.SendPropertyChanging
				Me._Brand = value
				Me.SendPropertyChanged("Brand")
				Me.OnBrandChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thanm", DbType:="NVarChar(MAX)")>  _
	Public Property thanm() As String
		Get
			Return Me._thanm
		End Get
		Set
			If (String.Equals(Me._thanm, value) = false) Then
				Me.OnthanmChanging(value)
				Me.SendPropertyChanging
				Me._thanm = value
				Me.SendPropertyChanged("thanm")
				Me.OnthanmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Status", DbType:="Int")>  _
	Public Property Status() As System.Nullable(Of Integer)
		Get
			Return Me._Status
		End Get
		Set
			If (Me._Status.Equals(value) = false) Then
				Me.OnStatusChanging(value)
				Me.SendPropertyChanging
				Me._Status = value
				Me.SendPropertyChanged("Status")
				Me.OnStatusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Addr", DbType:="NVarChar(MAX)")>  _
	Public Property Addr() As String
		Get
			Return Me._Addr
		End Get
		Set
			If (String.Equals(Me._Addr, value) = false) Then
				Me.OnAddrChanging(value)
				Me.SendPropertyChanging
				Me._Addr = value
				Me.SendPropertyChanged("Addr")
				Me.OnAddrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fdtypecd", DbType:="Int")>  _
	Public Property fdtypecd() As System.Nullable(Of Integer)
		Get
			Return Me._fdtypecd
		End Get
		Set
			If (Me._fdtypecd.Equals(value) = false) Then
				Me.OnfdtypecdChanging(value)
				Me.SendPropertyChanging
				Me._fdtypecd = value
				Me.SendPropertyChanged("fdtypecd")
				Me.OnfdtypecdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fdtypenm", DbType:="NVarChar(MAX)")>  _
	Public Property fdtypenm() As String
		Get
			Return Me._fdtypenm
		End Get
		Set
			If (String.Equals(Me._fdtypenm, value) = false) Then
				Me.OnfdtypenmChanging(value)
				Me.SendPropertyChanging
				Me._fdtypenm = value
				Me.SendPropertyChanged("fdtypenm")
				Me.OnfdtypenmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thanmowner", DbType:="NVarChar(MAX)")>  _
	Public Property thanmowner() As String
		Get
			Return Me._thanmowner
		End Get
		Set
			If (String.Equals(Me._thanmowner, value) = false) Then
				Me.OnthanmownerChanging(value)
				Me.SendPropertyChanging
				Me._thanmowner = value
				Me.SendPropertyChanged("thanmowner")
				Me.OnthanmownerChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EXP", DbType:="NVarChar(MAX)")>  _
	Public Property EXP() As String
		Get
			Return Me._EXP
		End Get
		Set
			If (String.Equals(Me._EXP, value) = false) Then
				Me.OnEXPChanging(value)
				Me.SendPropertyChanging
				Me._EXP = value
				Me.SendPropertyChanged("EXP")
				Me.OnEXPChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctlcnno", DbType:="NVarChar(MAX)")>  _
	Public Property lctlcnno() As String
		Get
			Return Me._lctlcnno
		End Get
		Set
			If (String.Equals(Me._lctlcnno, value) = false) Then
				Me.OnlctlcnnoChanging(value)
				Me.SendPropertyChanging
				Me._lctlcnno = value
				Me.SendPropertyChanged("lctlcnno")
				Me.OnlctlcnnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_AUTHORIZE", DbType:="NVarChar(MAX)")>  _
	Public Property CITIZEN_AUTHORIZE() As String
		Get
			Return Me._CITIZEN_AUTHORIZE
		End Get
		Set
			If (String.Equals(Me._CITIZEN_AUTHORIZE, value) = false) Then
				Me.OnCITIZEN_AUTHORIZEChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_AUTHORIZE = value
				Me.SendPropertyChanged("CITIZEN_AUTHORIZE")
				Me.OnCITIZEN_AUTHORIZEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SUBPDT", DbType:="NVarChar(MAX)")>  _
	Public Property SUBPDT() As String
		Get
			Return Me._SUBPDT
		End Get
		Set
			If (String.Equals(Me._SUBPDT, value) = false) Then
				Me.OnSUBPDTChanging(value)
				Me.SendPropertyChanging
				Me._SUBPDT = value
				Me.SendPropertyChanged("SUBPDT")
				Me.OnSUBPDTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MTHCD", DbType:="NVarChar(MAX)")>  _
	Public Property MTHCD() As String
		Get
			Return Me._MTHCD
		End Get
		Set
			If (String.Equals(Me._MTHCD, value) = false) Then
				Me.OnMTHCDChanging(value)
				Me.SendPropertyChanging
				Me._MTHCD = value
				Me.SendPropertyChanged("MTHCD")
				Me.OnMTHCDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_frgn_addr", DbType:="NVarChar(MAX)")>  _
	Public Property frgn_addr() As String
		Get
			Return Me._frgn_addr
		End Get
		Set
			If (String.Equals(Me._frgn_addr, value) = false) Then
				Me.Onfrgn_addrChanging(value)
				Me.SendPropertyChanging
				Me._frgn_addr = value
				Me.SendPropertyChanged("frgn_addr")
				Me.Onfrgn_addrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCN_STATUS", DbType:="Int")>  _
	Public Property LCN_STATUS() As System.Nullable(Of Integer)
		Get
			Return Me._LCN_STATUS
		End Get
		Set
			If (Me._LCN_STATUS.Equals(value) = false) Then
				Me.OnLCN_STATUSChanging(value)
				Me.SendPropertyChanging
				Me._LCN_STATUS = value
				Me.SendPropertyChanged("LCN_STATUS")
				Me.OnLCN_STATUSChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCN_STATUS_NAME", DbType:="NVarChar(MAX)")>  _
	Public Property LCN_STATUS_NAME() As String
		Get
			Return Me._LCN_STATUS_NAME
		End Get
		Set
			If (String.Equals(Me._LCN_STATUS_NAME, value) = false) Then
				Me.OnLCN_STATUS_NAMEChanging(value)
				Me.SendPropertyChanging
				Me._LCN_STATUS_NAME = value
				Me.SendPropertyChanged("LCN_STATUS_NAME")
				Me.OnLCN_STATUS_NAMEChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.XML_CMT")>  _
Partial Public Class XML_CMT
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _pvncd As System.Nullable(Of Short)
	
	Private _lctnmno As System.Nullable(Of Integer)
	
	Private _lcnsid As System.Nullable(Of Integer)
	
	Private _regnos As String
	
	Private _cmttypecd As System.Nullable(Of Short)
	
	Private _Brand_Tha As String
	
	Private _Brand_Eng As String
	
	Private _Productmain_tha As String
	
	Private _Productmain_eng As String
	
	Private _producttha As String
	
	Private _producteng As String
	
	Private _Producer_Name As String
	
	Private _Groupname As String
	
	Private _NewCode As String
	
	Private _Ranking As System.Nullable(Of Short)
	
	Private _cntcd As String
	
	Private _appvdate As System.Nullable(Of Date)
	
	Private _expdate As System.Nullable(Of Date)
	
	Private _DateCreate As System.Nullable(Of Date)
	
	Private _UpdateDate As System.Nullable(Of Date)
	
	Private _Itemno As System.Nullable(Of Integer)
	
	Private _cmtpdpstcd As String
	
	Private _IDA As Integer
	
	Private _rcvno As String
	
	Private _thanm As String
	
	Private _thanmowner As String
	
	Private _FULLADDR As String
	
	Private _cnsdcd As System.Nullable(Of Integer)
	
	Private _lctcd As System.Nullable(Of Integer)
	
	Private _lctnmcd As System.Nullable(Of Integer)
	
	Private _IDENTIFY As String
	
	Private _NAME_APPLICATION As String
	
	Private _applicability As String
	
	Private _mode As String
	
	Private _conditionP As String
	
	Private _conditionC As String
	
	Private _conditionS As String
	
	Private _postcnsdcd As System.Nullable(Of Short)
	
	Private _NAME_EMPLOYER As String
	
	Private _LOCATION_EMPLOYER As String
	
	Private _CITIEZEN_ID_AUTHORIZE As String
	
	Private _CANCEL_DATE As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnpvncdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnpvncdChanged()
    End Sub
    Partial Private Sub OnlctnmnoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlctnmnoChanged()
    End Sub
    Partial Private Sub OnlcnsidChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcnsidChanged()
    End Sub
    Partial Private Sub OnregnosChanging(value As String)
    End Sub
    Partial Private Sub OnregnosChanged()
    End Sub
    Partial Private Sub OncmttypecdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OncmttypecdChanged()
    End Sub
    Partial Private Sub OnBrand_ThaChanging(value As String)
    End Sub
    Partial Private Sub OnBrand_ThaChanged()
    End Sub
    Partial Private Sub OnBrand_EngChanging(value As String)
    End Sub
    Partial Private Sub OnBrand_EngChanged()
    End Sub
    Partial Private Sub OnProductmain_thaChanging(value As String)
    End Sub
    Partial Private Sub OnProductmain_thaChanged()
    End Sub
    Partial Private Sub OnProductmain_engChanging(value As String)
    End Sub
    Partial Private Sub OnProductmain_engChanged()
    End Sub
    Partial Private Sub OnproductthaChanging(value As String)
    End Sub
    Partial Private Sub OnproductthaChanged()
    End Sub
    Partial Private Sub OnproductengChanging(value As String)
    End Sub
    Partial Private Sub OnproductengChanged()
    End Sub
    Partial Private Sub OnProducer_NameChanging(value As String)
    End Sub
    Partial Private Sub OnProducer_NameChanged()
    End Sub
    Partial Private Sub OnGroupnameChanging(value As String)
    End Sub
    Partial Private Sub OnGroupnameChanged()
    End Sub
    Partial Private Sub OnNewCodeChanging(value As String)
    End Sub
    Partial Private Sub OnNewCodeChanged()
    End Sub
    Partial Private Sub OnRankingChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnRankingChanged()
    End Sub
    Partial Private Sub OncntcdChanging(value As String)
    End Sub
    Partial Private Sub OncntcdChanged()
    End Sub
    Partial Private Sub OnappvdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnappvdateChanged()
    End Sub
    Partial Private Sub OnexpdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnexpdateChanged()
    End Sub
    Partial Private Sub OnDateCreateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDateCreateChanged()
    End Sub
    Partial Private Sub OnUpdateDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnUpdateDateChanged()
    End Sub
    Partial Private Sub OnItemnoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnItemnoChanged()
    End Sub
    Partial Private Sub OncmtpdpstcdChanging(value As String)
    End Sub
    Partial Private Sub OncmtpdpstcdChanged()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnrcvnoChanging(value As String)
    End Sub
    Partial Private Sub OnrcvnoChanged()
    End Sub
    Partial Private Sub OnthanmChanging(value As String)
    End Sub
    Partial Private Sub OnthanmChanged()
    End Sub
    Partial Private Sub OnthanmownerChanging(value As String)
    End Sub
    Partial Private Sub OnthanmownerChanged()
    End Sub
    Partial Private Sub OnFULLADDRChanging(value As String)
    End Sub
    Partial Private Sub OnFULLADDRChanged()
    End Sub
    Partial Private Sub OncnsdcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OncnsdcdChanged()
    End Sub
    Partial Private Sub OnlctcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlctcdChanged()
    End Sub
    Partial Private Sub OnlctnmcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlctnmcdChanged()
    End Sub
    Partial Private Sub OnIDENTIFYChanging(value As String)
    End Sub
    Partial Private Sub OnIDENTIFYChanged()
    End Sub
    Partial Private Sub OnNAME_APPLICATIONChanging(value As String)
    End Sub
    Partial Private Sub OnNAME_APPLICATIONChanged()
    End Sub
    Partial Private Sub OnapplicabilityChanging(value As String)
    End Sub
    Partial Private Sub OnapplicabilityChanged()
    End Sub
    Partial Private Sub OnmodeChanging(value As String)
    End Sub
    Partial Private Sub OnmodeChanged()
    End Sub
    Partial Private Sub OnconditionPChanging(value As String)
    End Sub
    Partial Private Sub OnconditionPChanged()
    End Sub
    Partial Private Sub OnconditionCChanging(value As String)
    End Sub
    Partial Private Sub OnconditionCChanged()
    End Sub
    Partial Private Sub OnconditionSChanging(value As String)
    End Sub
    Partial Private Sub OnconditionSChanged()
    End Sub
    Partial Private Sub OnpostcnsdcdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnpostcnsdcdChanged()
    End Sub
    Partial Private Sub OnNAME_EMPLOYERChanging(value As String)
    End Sub
    Partial Private Sub OnNAME_EMPLOYERChanged()
    End Sub
    Partial Private Sub OnLOCATION_EMPLOYERChanging(value As String)
    End Sub
    Partial Private Sub OnLOCATION_EMPLOYERChanged()
    End Sub
    Partial Private Sub OnCITIEZEN_ID_AUTHORIZEChanging(value As String)
    End Sub
    Partial Private Sub OnCITIEZEN_ID_AUTHORIZEChanged()
    End Sub
    Partial Private Sub OnCANCEL_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCANCEL_DATEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pvncd", DbType:="SmallInt")>  _
	Public Property pvncd() As System.Nullable(Of Short)
		Get
			Return Me._pvncd
		End Get
		Set
			If (Me._pvncd.Equals(value) = false) Then
				Me.OnpvncdChanging(value)
				Me.SendPropertyChanging
				Me._pvncd = value
				Me.SendPropertyChanged("pvncd")
				Me.OnpvncdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctnmno", DbType:="Int")>  _
	Public Property lctnmno() As System.Nullable(Of Integer)
		Get
			Return Me._lctnmno
		End Get
		Set
			If (Me._lctnmno.Equals(value) = false) Then
				Me.OnlctnmnoChanging(value)
				Me.SendPropertyChanging
				Me._lctnmno = value
				Me.SendPropertyChanged("lctnmno")
				Me.OnlctnmnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnsid", DbType:="Int")>  _
	Public Property lcnsid() As System.Nullable(Of Integer)
		Get
			Return Me._lcnsid
		End Get
		Set
			If (Me._lcnsid.Equals(value) = false) Then
				Me.OnlcnsidChanging(value)
				Me.SendPropertyChanging
				Me._lcnsid = value
				Me.SendPropertyChanged("lcnsid")
				Me.OnlcnsidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_regnos", DbType:="NVarChar(MAX)")>  _
	Public Property regnos() As String
		Get
			Return Me._regnos
		End Get
		Set
			If (String.Equals(Me._regnos, value) = false) Then
				Me.OnregnosChanging(value)
				Me.SendPropertyChanging
				Me._regnos = value
				Me.SendPropertyChanged("regnos")
				Me.OnregnosChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cmttypecd", DbType:="SmallInt")>  _
	Public Property cmttypecd() As System.Nullable(Of Short)
		Get
			Return Me._cmttypecd
		End Get
		Set
			If (Me._cmttypecd.Equals(value) = false) Then
				Me.OncmttypecdChanging(value)
				Me.SendPropertyChanging
				Me._cmttypecd = value
				Me.SendPropertyChanged("cmttypecd")
				Me.OncmttypecdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Brand_Tha", DbType:="NVarChar(MAX)")>  _
	Public Property Brand_Tha() As String
		Get
			Return Me._Brand_Tha
		End Get
		Set
			If (String.Equals(Me._Brand_Tha, value) = false) Then
				Me.OnBrand_ThaChanging(value)
				Me.SendPropertyChanging
				Me._Brand_Tha = value
				Me.SendPropertyChanged("Brand_Tha")
				Me.OnBrand_ThaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Brand_Eng", DbType:="NVarChar(MAX)")>  _
	Public Property Brand_Eng() As String
		Get
			Return Me._Brand_Eng
		End Get
		Set
			If (String.Equals(Me._Brand_Eng, value) = false) Then
				Me.OnBrand_EngChanging(value)
				Me.SendPropertyChanging
				Me._Brand_Eng = value
				Me.SendPropertyChanged("Brand_Eng")
				Me.OnBrand_EngChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Productmain_tha", DbType:="NVarChar(MAX)")>  _
	Public Property Productmain_tha() As String
		Get
			Return Me._Productmain_tha
		End Get
		Set
			If (String.Equals(Me._Productmain_tha, value) = false) Then
				Me.OnProductmain_thaChanging(value)
				Me.SendPropertyChanging
				Me._Productmain_tha = value
				Me.SendPropertyChanged("Productmain_tha")
				Me.OnProductmain_thaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Productmain_eng", DbType:="NVarChar(MAX)")>  _
	Public Property Productmain_eng() As String
		Get
			Return Me._Productmain_eng
		End Get
		Set
			If (String.Equals(Me._Productmain_eng, value) = false) Then
				Me.OnProductmain_engChanging(value)
				Me.SendPropertyChanging
				Me._Productmain_eng = value
				Me.SendPropertyChanged("Productmain_eng")
				Me.OnProductmain_engChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_producttha", DbType:="NVarChar(MAX)")>  _
	Public Property producttha() As String
		Get
			Return Me._producttha
		End Get
		Set
			If (String.Equals(Me._producttha, value) = false) Then
				Me.OnproductthaChanging(value)
				Me.SendPropertyChanging
				Me._producttha = value
				Me.SendPropertyChanged("producttha")
				Me.OnproductthaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_producteng", DbType:="NVarChar(MAX)")>  _
	Public Property producteng() As String
		Get
			Return Me._producteng
		End Get
		Set
			If (String.Equals(Me._producteng, value) = false) Then
				Me.OnproductengChanging(value)
				Me.SendPropertyChanging
				Me._producteng = value
				Me.SendPropertyChanged("producteng")
				Me.OnproductengChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Producer_Name", DbType:="NVarChar(MAX)")>  _
	Public Property Producer_Name() As String
		Get
			Return Me._Producer_Name
		End Get
		Set
			If (String.Equals(Me._Producer_Name, value) = false) Then
				Me.OnProducer_NameChanging(value)
				Me.SendPropertyChanging
				Me._Producer_Name = value
				Me.SendPropertyChanged("Producer_Name")
				Me.OnProducer_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Groupname", DbType:="VarChar(2)")>  _
	Public Property Groupname() As String
		Get
			Return Me._Groupname
		End Get
		Set
			If (String.Equals(Me._Groupname, value) = false) Then
				Me.OnGroupnameChanging(value)
				Me.SendPropertyChanging
				Me._Groupname = value
				Me.SendPropertyChanged("Groupname")
				Me.OnGroupnameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NewCode", DbType:="NVarChar(MAX)")>  _
	Public Property NewCode() As String
		Get
			Return Me._NewCode
		End Get
		Set
			If (String.Equals(Me._NewCode, value) = false) Then
				Me.OnNewCodeChanging(value)
				Me.SendPropertyChanging
				Me._NewCode = value
				Me.SendPropertyChanged("NewCode")
				Me.OnNewCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Ranking", DbType:="SmallInt")>  _
	Public Property Ranking() As System.Nullable(Of Short)
		Get
			Return Me._Ranking
		End Get
		Set
			If (Me._Ranking.Equals(value) = false) Then
				Me.OnRankingChanging(value)
				Me.SendPropertyChanging
				Me._Ranking = value
				Me.SendPropertyChanged("Ranking")
				Me.OnRankingChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cntcd", DbType:="NVarChar(50)")>  _
	Public Property cntcd() As String
		Get
			Return Me._cntcd
		End Get
		Set
			If (String.Equals(Me._cntcd, value) = false) Then
				Me.OncntcdChanging(value)
				Me.SendPropertyChanging
				Me._cntcd = value
				Me.SendPropertyChanged("cntcd")
				Me.OncntcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_appvdate", DbType:="DateTime2")>  _
	Public Property appvdate() As System.Nullable(Of Date)
		Get
			Return Me._appvdate
		End Get
		Set
			If (Me._appvdate.Equals(value) = false) Then
				Me.OnappvdateChanging(value)
				Me.SendPropertyChanging
				Me._appvdate = value
				Me.SendPropertyChanged("appvdate")
				Me.OnappvdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_expdate", DbType:="Date")>  _
	Public Property expdate() As System.Nullable(Of Date)
		Get
			Return Me._expdate
		End Get
		Set
			If (Me._expdate.Equals(value) = false) Then
				Me.OnexpdateChanging(value)
				Me.SendPropertyChanging
				Me._expdate = value
				Me.SendPropertyChanged("expdate")
				Me.OnexpdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateCreate", DbType:="DateTime")>  _
	Public Property DateCreate() As System.Nullable(Of Date)
		Get
			Return Me._DateCreate
		End Get
		Set
			If (Me._DateCreate.Equals(value) = false) Then
				Me.OnDateCreateChanging(value)
				Me.SendPropertyChanging
				Me._DateCreate = value
				Me.SendPropertyChanged("DateCreate")
				Me.OnDateCreateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UpdateDate", DbType:="DateTime")>  _
	Public Property UpdateDate() As System.Nullable(Of Date)
		Get
			Return Me._UpdateDate
		End Get
		Set
			If (Me._UpdateDate.Equals(value) = false) Then
				Me.OnUpdateDateChanging(value)
				Me.SendPropertyChanging
				Me._UpdateDate = value
				Me.SendPropertyChanged("UpdateDate")
				Me.OnUpdateDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Itemno", DbType:="Int")>  _
	Public Property Itemno() As System.Nullable(Of Integer)
		Get
			Return Me._Itemno
		End Get
		Set
			If (Me._Itemno.Equals(value) = false) Then
				Me.OnItemnoChanging(value)
				Me.SendPropertyChanging
				Me._Itemno = value
				Me.SendPropertyChanged("Itemno")
				Me.OnItemnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cmtpdpstcd", DbType:="NChar(10)")>  _
	Public Property cmtpdpstcd() As String
		Get
			Return Me._cmtpdpstcd
		End Get
		Set
			If (String.Equals(Me._cmtpdpstcd, value) = false) Then
				Me.OncmtpdpstcdChanging(value)
				Me.SendPropertyChanging
				Me._cmtpdpstcd = value
				Me.SendPropertyChanged("cmtpdpstcd")
				Me.OncmtpdpstcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rcvno", DbType:="VarChar(50)")>  _
	Public Property rcvno() As String
		Get
			Return Me._rcvno
		End Get
		Set
			If (String.Equals(Me._rcvno, value) = false) Then
				Me.OnrcvnoChanging(value)
				Me.SendPropertyChanging
				Me._rcvno = value
				Me.SendPropertyChanged("rcvno")
				Me.OnrcvnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thanm", DbType:="NVarChar(MAX)")>  _
	Public Property thanm() As String
		Get
			Return Me._thanm
		End Get
		Set
			If (String.Equals(Me._thanm, value) = false) Then
				Me.OnthanmChanging(value)
				Me.SendPropertyChanging
				Me._thanm = value
				Me.SendPropertyChanged("thanm")
				Me.OnthanmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thanmowner", DbType:="NVarChar(MAX)")>  _
	Public Property thanmowner() As String
		Get
			Return Me._thanmowner
		End Get
		Set
			If (String.Equals(Me._thanmowner, value) = false) Then
				Me.OnthanmownerChanging(value)
				Me.SendPropertyChanging
				Me._thanmowner = value
				Me.SendPropertyChanged("thanmowner")
				Me.OnthanmownerChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FULLADDR", DbType:="NVarChar(MAX)")>  _
	Public Property FULLADDR() As String
		Get
			Return Me._FULLADDR
		End Get
		Set
			If (String.Equals(Me._FULLADDR, value) = false) Then
				Me.OnFULLADDRChanging(value)
				Me.SendPropertyChanging
				Me._FULLADDR = value
				Me.SendPropertyChanged("FULLADDR")
				Me.OnFULLADDRChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cnsdcd", DbType:="Int")>  _
	Public Property cnsdcd() As System.Nullable(Of Integer)
		Get
			Return Me._cnsdcd
		End Get
		Set
			If (Me._cnsdcd.Equals(value) = false) Then
				Me.OncnsdcdChanging(value)
				Me.SendPropertyChanging
				Me._cnsdcd = value
				Me.SendPropertyChanged("cnsdcd")
				Me.OncnsdcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctcd", DbType:="Int")>  _
	Public Property lctcd() As System.Nullable(Of Integer)
		Get
			Return Me._lctcd
		End Get
		Set
			If (Me._lctcd.Equals(value) = false) Then
				Me.OnlctcdChanging(value)
				Me.SendPropertyChanging
				Me._lctcd = value
				Me.SendPropertyChanged("lctcd")
				Me.OnlctcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctnmcd", DbType:="Int")>  _
	Public Property lctnmcd() As System.Nullable(Of Integer)
		Get
			Return Me._lctnmcd
		End Get
		Set
			If (Me._lctnmcd.Equals(value) = false) Then
				Me.OnlctnmcdChanging(value)
				Me.SendPropertyChanging
				Me._lctnmcd = value
				Me.SendPropertyChanged("lctnmcd")
				Me.OnlctnmcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDENTIFY", DbType:="NVarChar(MAX)")>  _
	Public Property IDENTIFY() As String
		Get
			Return Me._IDENTIFY
		End Get
		Set
			If (String.Equals(Me._IDENTIFY, value) = false) Then
				Me.OnIDENTIFYChanging(value)
				Me.SendPropertyChanging
				Me._IDENTIFY = value
				Me.SendPropertyChanged("IDENTIFY")
				Me.OnIDENTIFYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NAME_APPLICATION", DbType:="NVarChar(MAX)")>  _
	Public Property NAME_APPLICATION() As String
		Get
			Return Me._NAME_APPLICATION
		End Get
		Set
			If (String.Equals(Me._NAME_APPLICATION, value) = false) Then
				Me.OnNAME_APPLICATIONChanging(value)
				Me.SendPropertyChanging
				Me._NAME_APPLICATION = value
				Me.SendPropertyChanged("NAME_APPLICATION")
				Me.OnNAME_APPLICATIONChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_applicability", DbType:="NVarChar(MAX)")>  _
	Public Property applicability() As String
		Get
			Return Me._applicability
		End Get
		Set
			If (String.Equals(Me._applicability, value) = false) Then
				Me.OnapplicabilityChanging(value)
				Me.SendPropertyChanging
				Me._applicability = value
				Me.SendPropertyChanged("applicability")
				Me.OnapplicabilityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_mode", DbType:="NVarChar(MAX)")>  _
	Public Property mode() As String
		Get
			Return Me._mode
		End Get
		Set
			If (String.Equals(Me._mode, value) = false) Then
				Me.OnmodeChanging(value)
				Me.SendPropertyChanging
				Me._mode = value
				Me.SendPropertyChanged("mode")
				Me.OnmodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_conditionP", DbType:="NVarChar(MAX)")>  _
	Public Property conditionP() As String
		Get
			Return Me._conditionP
		End Get
		Set
			If (String.Equals(Me._conditionP, value) = false) Then
				Me.OnconditionPChanging(value)
				Me.SendPropertyChanging
				Me._conditionP = value
				Me.SendPropertyChanged("conditionP")
				Me.OnconditionPChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_conditionC", DbType:="NVarChar(MAX)")>  _
	Public Property conditionC() As String
		Get
			Return Me._conditionC
		End Get
		Set
			If (String.Equals(Me._conditionC, value) = false) Then
				Me.OnconditionCChanging(value)
				Me.SendPropertyChanging
				Me._conditionC = value
				Me.SendPropertyChanged("conditionC")
				Me.OnconditionCChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_conditionS", DbType:="NVarChar(MAX)")>  _
	Public Property conditionS() As String
		Get
			Return Me._conditionS
		End Get
		Set
			If (String.Equals(Me._conditionS, value) = false) Then
				Me.OnconditionSChanging(value)
				Me.SendPropertyChanging
				Me._conditionS = value
				Me.SendPropertyChanged("conditionS")
				Me.OnconditionSChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_postcnsdcd", DbType:="SmallInt")>  _
	Public Property postcnsdcd() As System.Nullable(Of Short)
		Get
			Return Me._postcnsdcd
		End Get
		Set
			If (Me._postcnsdcd.Equals(value) = false) Then
				Me.OnpostcnsdcdChanging(value)
				Me.SendPropertyChanging
				Me._postcnsdcd = value
				Me.SendPropertyChanged("postcnsdcd")
				Me.OnpostcnsdcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NAME_EMPLOYER", DbType:="NVarChar(MAX)")>  _
	Public Property NAME_EMPLOYER() As String
		Get
			Return Me._NAME_EMPLOYER
		End Get
		Set
			If (String.Equals(Me._NAME_EMPLOYER, value) = false) Then
				Me.OnNAME_EMPLOYERChanging(value)
				Me.SendPropertyChanging
				Me._NAME_EMPLOYER = value
				Me.SendPropertyChanged("NAME_EMPLOYER")
				Me.OnNAME_EMPLOYERChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LOCATION_EMPLOYER", DbType:="NVarChar(MAX)")>  _
	Public Property LOCATION_EMPLOYER() As String
		Get
			Return Me._LOCATION_EMPLOYER
		End Get
		Set
			If (String.Equals(Me._LOCATION_EMPLOYER, value) = false) Then
				Me.OnLOCATION_EMPLOYERChanging(value)
				Me.SendPropertyChanging
				Me._LOCATION_EMPLOYER = value
				Me.SendPropertyChanged("LOCATION_EMPLOYER")
				Me.OnLOCATION_EMPLOYERChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIEZEN_ID_AUTHORIZE", DbType:="NVarChar(MAX)")>  _
	Public Property CITIEZEN_ID_AUTHORIZE() As String
		Get
			Return Me._CITIEZEN_ID_AUTHORIZE
		End Get
		Set
			If (String.Equals(Me._CITIEZEN_ID_AUTHORIZE, value) = false) Then
				Me.OnCITIEZEN_ID_AUTHORIZEChanging(value)
				Me.SendPropertyChanging
				Me._CITIEZEN_ID_AUTHORIZE = value
				Me.SendPropertyChanged("CITIEZEN_ID_AUTHORIZE")
				Me.OnCITIEZEN_ID_AUTHORIZEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CANCEL_DATE", DbType:="DateTime")>  _
	Public Property CANCEL_DATE() As System.Nullable(Of Date)
		Get
			Return Me._CANCEL_DATE
		End Get
		Set
			If (Me._CANCEL_DATE.Equals(value) = false) Then
				Me.OnCANCEL_DATEChanging(value)
				Me.SendPropertyChanging
				Me._CANCEL_DATE = value
				Me.SendPropertyChanged("CANCEL_DATE")
				Me.OnCANCEL_DATEChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.XML_TXC")>  _
Partial Public Class XML_TXC
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _pvncd As System.Nullable(Of Short)
	
	Private _lcnno As System.Nullable(Of Integer)
	
	Private _rgno As String
	
	Private _lcnsid As System.Nullable(Of Integer)
	
	Private _lcntpcd As System.Nullable(Of Short)
	
	Private _rcvdate As System.Nullable(Of Date)
	
	Private _expdate As System.Nullable(Of Date)
	
	Private _ttrdnm As String
	
	Private _etrdnm As String
	
	Private _fpdnm As String
	
	Private _cntcd As String
	
	Private _rid As System.Nullable(Of Short)
	
	Private _GrouNAME As String
	
	Private _Newcode As String
	
	Private _Ranking As String
	
	Private _IDA As Integer
	
	Private _lctcd As System.Nullable(Of Integer)
	
	Private _lctnmcd As System.Nullable(Of Integer)
	
	Private _CITIZEN_ID As String
	
	Private _FULL_ADDR As String
	
	Private _lct_name As String
	
	Private _owner_name As String
	
	Private _LCN_DISPLAY As String
	
	Private _LCN_SEARCH As String
	
	Private _IDENTIFY As String
	
	Private _LCN_SEARCH2 As String
	
	Private _STATUS_ID As System.Nullable(Of Integer)
	
	Private _STATUS_NAME As String
	
	Private _LICENSE_TYPE_NAME As String
	
	Private _LCNTPCD_NAME As String
	
	Private _sqtlcn As String
	
	Private _qunit As String
	
	Private _qunitnm As String
	
	Private _cncnm As String
	
	Private _engfrgnnm As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnpvncdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnpvncdChanged()
    End Sub
    Partial Private Sub OnlcnnoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcnnoChanged()
    End Sub
    Partial Private Sub OnrgnoChanging(value As String)
    End Sub
    Partial Private Sub OnrgnoChanged()
    End Sub
    Partial Private Sub OnlcnsidChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlcnsidChanged()
    End Sub
    Partial Private Sub OnlcntpcdChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnlcntpcdChanged()
    End Sub
    Partial Private Sub OnrcvdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnrcvdateChanged()
    End Sub
    Partial Private Sub OnexpdateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnexpdateChanged()
    End Sub
    Partial Private Sub OnttrdnmChanging(value As String)
    End Sub
    Partial Private Sub OnttrdnmChanged()
    End Sub
    Partial Private Sub OnetrdnmChanging(value As String)
    End Sub
    Partial Private Sub OnetrdnmChanged()
    End Sub
    Partial Private Sub OnfpdnmChanging(value As String)
    End Sub
    Partial Private Sub OnfpdnmChanged()
    End Sub
    Partial Private Sub OncntcdChanging(value As String)
    End Sub
    Partial Private Sub OncntcdChanged()
    End Sub
    Partial Private Sub OnridChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnridChanged()
    End Sub
    Partial Private Sub OnGrouNAMEChanging(value As String)
    End Sub
    Partial Private Sub OnGrouNAMEChanged()
    End Sub
    Partial Private Sub OnNewcodeChanging(value As String)
    End Sub
    Partial Private Sub OnNewcodeChanged()
    End Sub
    Partial Private Sub OnRankingChanging(value As String)
    End Sub
    Partial Private Sub OnRankingChanged()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnlctcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlctcdChanged()
    End Sub
    Partial Private Sub OnlctnmcdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnlctnmcdChanged()
    End Sub
    Partial Private Sub OnCITIZEN_IDChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_IDChanged()
    End Sub
    Partial Private Sub OnFULL_ADDRChanging(value As String)
    End Sub
    Partial Private Sub OnFULL_ADDRChanged()
    End Sub
    Partial Private Sub Onlct_nameChanging(value As String)
    End Sub
    Partial Private Sub Onlct_nameChanged()
    End Sub
    Partial Private Sub Onowner_nameChanging(value As String)
    End Sub
    Partial Private Sub Onowner_nameChanged()
    End Sub
    Partial Private Sub OnLCN_DISPLAYChanging(value As String)
    End Sub
    Partial Private Sub OnLCN_DISPLAYChanged()
    End Sub
    Partial Private Sub OnLCN_SEARCHChanging(value As String)
    End Sub
    Partial Private Sub OnLCN_SEARCHChanged()
    End Sub
    Partial Private Sub OnIDENTIFYChanging(value As String)
    End Sub
    Partial Private Sub OnIDENTIFYChanged()
    End Sub
    Partial Private Sub OnLCN_SEARCH2Changing(value As String)
    End Sub
    Partial Private Sub OnLCN_SEARCH2Changed()
    End Sub
    Partial Private Sub OnSTATUS_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSTATUS_IDChanged()
    End Sub
    Partial Private Sub OnSTATUS_NAMEChanging(value As String)
    End Sub
    Partial Private Sub OnSTATUS_NAMEChanged()
    End Sub
    Partial Private Sub OnLICENSE_TYPE_NAMEChanging(value As String)
    End Sub
    Partial Private Sub OnLICENSE_TYPE_NAMEChanged()
    End Sub
    Partial Private Sub OnLCNTPCD_NAMEChanging(value As String)
    End Sub
    Partial Private Sub OnLCNTPCD_NAMEChanged()
    End Sub
    Partial Private Sub OnsqtlcnChanging(value As String)
    End Sub
    Partial Private Sub OnsqtlcnChanged()
    End Sub
    Partial Private Sub OnqunitChanging(value As String)
    End Sub
    Partial Private Sub OnqunitChanged()
    End Sub
    Partial Private Sub OnqunitnmChanging(value As String)
    End Sub
    Partial Private Sub OnqunitnmChanged()
    End Sub
    Partial Private Sub OncncnmChanging(value As String)
    End Sub
    Partial Private Sub OncncnmChanged()
    End Sub
    Partial Private Sub OnengfrgnnmChanging(value As String)
    End Sub
    Partial Private Sub OnengfrgnnmChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pvncd", DbType:="SmallInt")>  _
	Public Property pvncd() As System.Nullable(Of Short)
		Get
			Return Me._pvncd
		End Get
		Set
			If (Me._pvncd.Equals(value) = false) Then
				Me.OnpvncdChanging(value)
				Me.SendPropertyChanging
				Me._pvncd = value
				Me.SendPropertyChanged("pvncd")
				Me.OnpvncdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnno", DbType:="Int")>  _
	Public Property lcnno() As System.Nullable(Of Integer)
		Get
			Return Me._lcnno
		End Get
		Set
			If (Me._lcnno.Equals(value) = false) Then
				Me.OnlcnnoChanging(value)
				Me.SendPropertyChanging
				Me._lcnno = value
				Me.SendPropertyChanged("lcnno")
				Me.OnlcnnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rgno", DbType:="NVarChar(MAX)")>  _
	Public Property rgno() As String
		Get
			Return Me._rgno
		End Get
		Set
			If (String.Equals(Me._rgno, value) = false) Then
				Me.OnrgnoChanging(value)
				Me.SendPropertyChanging
				Me._rgno = value
				Me.SendPropertyChanged("rgno")
				Me.OnrgnoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcnsid", DbType:="Int")>  _
	Public Property lcnsid() As System.Nullable(Of Integer)
		Get
			Return Me._lcnsid
		End Get
		Set
			If (Me._lcnsid.Equals(value) = false) Then
				Me.OnlcnsidChanging(value)
				Me.SendPropertyChanging
				Me._lcnsid = value
				Me.SendPropertyChanged("lcnsid")
				Me.OnlcnsidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lcntpcd", DbType:="SmallInt")>  _
	Public Property lcntpcd() As System.Nullable(Of Short)
		Get
			Return Me._lcntpcd
		End Get
		Set
			If (Me._lcntpcd.Equals(value) = false) Then
				Me.OnlcntpcdChanging(value)
				Me.SendPropertyChanging
				Me._lcntpcd = value
				Me.SendPropertyChanged("lcntpcd")
				Me.OnlcntpcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rcvdate", DbType:="DateTime2")>  _
	Public Property rcvdate() As System.Nullable(Of Date)
		Get
			Return Me._rcvdate
		End Get
		Set
			If (Me._rcvdate.Equals(value) = false) Then
				Me.OnrcvdateChanging(value)
				Me.SendPropertyChanging
				Me._rcvdate = value
				Me.SendPropertyChanged("rcvdate")
				Me.OnrcvdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_expdate", DbType:="Date")>  _
	Public Property expdate() As System.Nullable(Of Date)
		Get
			Return Me._expdate
		End Get
		Set
			If (Me._expdate.Equals(value) = false) Then
				Me.OnexpdateChanging(value)
				Me.SendPropertyChanging
				Me._expdate = value
				Me.SendPropertyChanged("expdate")
				Me.OnexpdateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ttrdnm", DbType:="NVarChar(MAX)")>  _
	Public Property ttrdnm() As String
		Get
			Return Me._ttrdnm
		End Get
		Set
			If (String.Equals(Me._ttrdnm, value) = false) Then
				Me.OnttrdnmChanging(value)
				Me.SendPropertyChanging
				Me._ttrdnm = value
				Me.SendPropertyChanged("ttrdnm")
				Me.OnttrdnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_etrdnm", DbType:="NVarChar(MAX)")>  _
	Public Property etrdnm() As String
		Get
			Return Me._etrdnm
		End Get
		Set
			If (String.Equals(Me._etrdnm, value) = false) Then
				Me.OnetrdnmChanging(value)
				Me.SendPropertyChanging
				Me._etrdnm = value
				Me.SendPropertyChanged("etrdnm")
				Me.OnetrdnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fpdnm", DbType:="NVarChar(MAX)")>  _
	Public Property fpdnm() As String
		Get
			Return Me._fpdnm
		End Get
		Set
			If (String.Equals(Me._fpdnm, value) = false) Then
				Me.OnfpdnmChanging(value)
				Me.SendPropertyChanging
				Me._fpdnm = value
				Me.SendPropertyChanged("fpdnm")
				Me.OnfpdnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cntcd", DbType:="Char(3)")>  _
	Public Property cntcd() As String
		Get
			Return Me._cntcd
		End Get
		Set
			If (String.Equals(Me._cntcd, value) = false) Then
				Me.OncntcdChanging(value)
				Me.SendPropertyChanging
				Me._cntcd = value
				Me.SendPropertyChanged("cntcd")
				Me.OncntcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rid", DbType:="SmallInt")>  _
	Public Property rid() As System.Nullable(Of Short)
		Get
			Return Me._rid
		End Get
		Set
			If (Me._rid.Equals(value) = false) Then
				Me.OnridChanging(value)
				Me.SendPropertyChanging
				Me._rid = value
				Me.SendPropertyChanged("rid")
				Me.OnridChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GrouNAME", DbType:="VarChar(2)")>  _
	Public Property GrouNAME() As String
		Get
			Return Me._GrouNAME
		End Get
		Set
			If (String.Equals(Me._GrouNAME, value) = false) Then
				Me.OnGrouNAMEChanging(value)
				Me.SendPropertyChanging
				Me._GrouNAME = value
				Me.SendPropertyChanged("GrouNAME")
				Me.OnGrouNAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Newcode", DbType:="NVarChar(448)")>  _
	Public Property Newcode() As String
		Get
			Return Me._Newcode
		End Get
		Set
			If (String.Equals(Me._Newcode, value) = false) Then
				Me.OnNewcodeChanging(value)
				Me.SendPropertyChanging
				Me._Newcode = value
				Me.SendPropertyChanged("Newcode")
				Me.OnNewcodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Ranking", DbType:="NVarChar(50)")>  _
	Public Property Ranking() As String
		Get
			Return Me._Ranking
		End Get
		Set
			If (String.Equals(Me._Ranking, value) = false) Then
				Me.OnRankingChanging(value)
				Me.SendPropertyChanging
				Me._Ranking = value
				Me.SendPropertyChanged("Ranking")
				Me.OnRankingChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctcd", DbType:="Int")>  _
	Public Property lctcd() As System.Nullable(Of Integer)
		Get
			Return Me._lctcd
		End Get
		Set
			If (Me._lctcd.Equals(value) = false) Then
				Me.OnlctcdChanging(value)
				Me.SendPropertyChanging
				Me._lctcd = value
				Me.SendPropertyChanged("lctcd")
				Me.OnlctcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lctnmcd", DbType:="Int")>  _
	Public Property lctnmcd() As System.Nullable(Of Integer)
		Get
			Return Me._lctnmcd
		End Get
		Set
			If (Me._lctnmcd.Equals(value) = false) Then
				Me.OnlctnmcdChanging(value)
				Me.SendPropertyChanging
				Me._lctnmcd = value
				Me.SendPropertyChanged("lctnmcd")
				Me.OnlctnmcdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_ID", DbType:="VarChar(50)")>  _
	Public Property CITIZEN_ID() As String
		Get
			Return Me._CITIZEN_ID
		End Get
		Set
			If (String.Equals(Me._CITIZEN_ID, value) = false) Then
				Me.OnCITIZEN_IDChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_ID = value
				Me.SendPropertyChanged("CITIZEN_ID")
				Me.OnCITIZEN_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FULL_ADDR", DbType:="VarChar(MAX)")>  _
	Public Property FULL_ADDR() As String
		Get
			Return Me._FULL_ADDR
		End Get
		Set
			If (String.Equals(Me._FULL_ADDR, value) = false) Then
				Me.OnFULL_ADDRChanging(value)
				Me.SendPropertyChanging
				Me._FULL_ADDR = value
				Me.SendPropertyChanged("FULL_ADDR")
				Me.OnFULL_ADDRChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lct_name", DbType:="VarChar(MAX)")>  _
	Public Property lct_name() As String
		Get
			Return Me._lct_name
		End Get
		Set
			If (String.Equals(Me._lct_name, value) = false) Then
				Me.Onlct_nameChanging(value)
				Me.SendPropertyChanging
				Me._lct_name = value
				Me.SendPropertyChanged("lct_name")
				Me.Onlct_nameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_owner_name", DbType:="VarChar(MAX)")>  _
	Public Property owner_name() As String
		Get
			Return Me._owner_name
		End Get
		Set
			If (String.Equals(Me._owner_name, value) = false) Then
				Me.Onowner_nameChanging(value)
				Me.SendPropertyChanging
				Me._owner_name = value
				Me.SendPropertyChanged("owner_name")
				Me.Onowner_nameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCN_DISPLAY", DbType:="NVarChar(MAX)")>  _
	Public Property LCN_DISPLAY() As String
		Get
			Return Me._LCN_DISPLAY
		End Get
		Set
			If (String.Equals(Me._LCN_DISPLAY, value) = false) Then
				Me.OnLCN_DISPLAYChanging(value)
				Me.SendPropertyChanging
				Me._LCN_DISPLAY = value
				Me.SendPropertyChanged("LCN_DISPLAY")
				Me.OnLCN_DISPLAYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCN_SEARCH", DbType:="VarChar(50)")>  _
	Public Property LCN_SEARCH() As String
		Get
			Return Me._LCN_SEARCH
		End Get
		Set
			If (String.Equals(Me._LCN_SEARCH, value) = false) Then
				Me.OnLCN_SEARCHChanging(value)
				Me.SendPropertyChanging
				Me._LCN_SEARCH = value
				Me.SendPropertyChanged("LCN_SEARCH")
				Me.OnLCN_SEARCHChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDENTIFY", DbType:="NVarChar(MAX)")>  _
	Public Property IDENTIFY() As String
		Get
			Return Me._IDENTIFY
		End Get
		Set
			If (String.Equals(Me._IDENTIFY, value) = false) Then
				Me.OnIDENTIFYChanging(value)
				Me.SendPropertyChanging
				Me._IDENTIFY = value
				Me.SendPropertyChanged("IDENTIFY")
				Me.OnIDENTIFYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCN_SEARCH2", DbType:="NVarChar(MAX)")>  _
	Public Property LCN_SEARCH2() As String
		Get
			Return Me._LCN_SEARCH2
		End Get
		Set
			If (String.Equals(Me._LCN_SEARCH2, value) = false) Then
				Me.OnLCN_SEARCH2Changing(value)
				Me.SendPropertyChanging
				Me._LCN_SEARCH2 = value
				Me.SendPropertyChanged("LCN_SEARCH2")
				Me.OnLCN_SEARCH2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STATUS_ID", DbType:="Int")>  _
	Public Property STATUS_ID() As System.Nullable(Of Integer)
		Get
			Return Me._STATUS_ID
		End Get
		Set
			If (Me._STATUS_ID.Equals(value) = false) Then
				Me.OnSTATUS_IDChanging(value)
				Me.SendPropertyChanging
				Me._STATUS_ID = value
				Me.SendPropertyChanged("STATUS_ID")
				Me.OnSTATUS_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STATUS_NAME", DbType:="NVarChar(MAX)")>  _
	Public Property STATUS_NAME() As String
		Get
			Return Me._STATUS_NAME
		End Get
		Set
			If (String.Equals(Me._STATUS_NAME, value) = false) Then
				Me.OnSTATUS_NAMEChanging(value)
				Me.SendPropertyChanging
				Me._STATUS_NAME = value
				Me.SendPropertyChanged("STATUS_NAME")
				Me.OnSTATUS_NAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LICENSE_TYPE_NAME", DbType:="NVarChar(MAX)")>  _
	Public Property LICENSE_TYPE_NAME() As String
		Get
			Return Me._LICENSE_TYPE_NAME
		End Get
		Set
			If (String.Equals(Me._LICENSE_TYPE_NAME, value) = false) Then
				Me.OnLICENSE_TYPE_NAMEChanging(value)
				Me.SendPropertyChanging
				Me._LICENSE_TYPE_NAME = value
				Me.SendPropertyChanged("LICENSE_TYPE_NAME")
				Me.OnLICENSE_TYPE_NAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCNTPCD_NAME", DbType:="NVarChar(MAX)")>  _
	Public Property LCNTPCD_NAME() As String
		Get
			Return Me._LCNTPCD_NAME
		End Get
		Set
			If (String.Equals(Me._LCNTPCD_NAME, value) = false) Then
				Me.OnLCNTPCD_NAMEChanging(value)
				Me.SendPropertyChanging
				Me._LCNTPCD_NAME = value
				Me.SendPropertyChanged("LCNTPCD_NAME")
				Me.OnLCNTPCD_NAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sqtlcn", DbType:="NVarChar(MAX)")>  _
	Public Property sqtlcn() As String
		Get
			Return Me._sqtlcn
		End Get
		Set
			If (String.Equals(Me._sqtlcn, value) = false) Then
				Me.OnsqtlcnChanging(value)
				Me.SendPropertyChanging
				Me._sqtlcn = value
				Me.SendPropertyChanged("sqtlcn")
				Me.OnsqtlcnChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_qunit", DbType:="NVarChar(MAX)")>  _
	Public Property qunit() As String
		Get
			Return Me._qunit
		End Get
		Set
			If (String.Equals(Me._qunit, value) = false) Then
				Me.OnqunitChanging(value)
				Me.SendPropertyChanging
				Me._qunit = value
				Me.SendPropertyChanged("qunit")
				Me.OnqunitChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_qunitnm", DbType:="NVarChar(MAX)")>  _
	Public Property qunitnm() As String
		Get
			Return Me._qunitnm
		End Get
		Set
			If (String.Equals(Me._qunitnm, value) = false) Then
				Me.OnqunitnmChanging(value)
				Me.SendPropertyChanging
				Me._qunitnm = value
				Me.SendPropertyChanged("qunitnm")
				Me.OnqunitnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cncnm", DbType:="NVarChar(MAX)")>  _
	Public Property cncnm() As String
		Get
			Return Me._cncnm
		End Get
		Set
			If (String.Equals(Me._cncnm, value) = false) Then
				Me.OncncnmChanging(value)
				Me.SendPropertyChanging
				Me._cncnm = value
				Me.SendPropertyChanged("cncnm")
				Me.OncncnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_engfrgnnm", DbType:="NVarChar(MAX)")>  _
	Public Property engfrgnnm() As String
		Get
			Return Me._engfrgnnm
		End Get
		Set
			If (String.Equals(Me._engfrgnnm, value) = false) Then
				Me.OnengfrgnnmChanging(value)
				Me.SendPropertyChanging
				Me._engfrgnnm = value
				Me.SendPropertyChanged("engfrgnnm")
				Me.OnengfrgnnmChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
